src/projector.ts

Perhaps it'd be useful to expose [Maquette's `replace` method](http://maquettejs.org/docs/typedoc/interfaces/_maquette_.projector.html#replace) to the projector. Changes `Projector#attach()` to take an options object.
Ideally we remove the previous implementation.
I'm not sure what (if anything) the `append` option to `createProjector()` does. It doesn't seem to be referenced in the `attach` method.

Suggestion to add replace option to Projector#attach()

---

src/mixins/createCachedRenderMixin.ts
tests/functional/all.ts
tests/functional/widgetClasses.html
tests/functional/widgetClasses.ts
tests/functional/widgetClassesFunctional.ts
tests/unit/mixins/createCachedRenderMixin.ts
tsconfig.json

Add support to remove classes previously applied to widgets via the widget's state.
Addresses issue #6

Support removing classes from Widgets 

---

src/projector.ts

Update Projector docs

---

src/mixins/createFormFieldMixin.ts
tests/unit/mixins/createFormFieldMixin.ts

Fix issue when rendering a falsey form widget value

---

.gitignore
.travis.yml
package.json
src/createDijit.ts
src/createResizePanel.ts
src/mixins/createCachedRenderMixin.ts
src/mixins/createCloseableMixin.ts
src/mixins/createFormFieldMixin.ts
src/mixins/createListMixin.ts
src/mixins/createParentListMixin.ts
src/mixins/createParentMapMixin.ts
src/mixins/createRenderable.ts
src/mixins/createRenderableChildrenMixin.ts
src/mixins/createTabbedMixin.ts
src/mixins/createVNodeEvented.ts
src/projector.ts
src/util/createMemoryStore.ts
tests/functional/tabbedPanelFunctional.ts
tests/functional/widgetClassesFunctional.ts
tests/functional/widgetsFunctional.ts
tests/unit/createDijit.ts
tests/unit/mixins/createParentListMixin.ts
tests/unit/mixins/createRenderable.ts
tests/unit/mixins/createStatefulChildrenMixin.ts
tests/unit/mixins/createStatefulListenersMixin.ts
tests/unit/projector.ts
tests/unit/util/createCancelableEvent.ts
tests/unit/util/createMemoryStore.ts
tsconfig.json
typings.json

Dependant on has, shim, core & compose TS2.0 updates
Fixes #1

Migration to TS2.0

---

src/createDijit.ts
src/mixins/createCachedRenderMixin.ts
src/mixins/createParentListMixin.ts
src/mixins/createParentMapMixin.ts
src/mixins/createStatefulChildrenMixin.ts
src/mixins/createStatefulListenersMixin.ts

Per <https://github.com/dojo/shim/issues/6>.

Avoid needlessly deleting WeakMap entries

---

package.json
src/examples/index.html
src/examples/scratch.html
tests/functional/tabbedPanel.html
tests/functional/widgetClasses.html
tests/functional/widgets.html
tests/intern.ts

Requires release of dojo-loader
Issue reference: https://github.com/dojo/meta/issues/73

update ready for the flat loader package

---

src/mixins/createRenderableChildrenMixin.ts
tests/unit/mixins/createRenderableChildrenMixin.ts

RenderableChildrenMixin now checks for assignment of children

---

README.md

**Type:** documentation
Minor update to the readme for consistency with other packages.
[ci skip]

Update readme to be consistent with alpha packages

---

tests/intern-saucelabs.ts

update ios version for tests

---

tests/intern-saucelabs.ts

Update Android version from 4.4 to 5.1

---

package.json
src/mixins/createParentListMixin.ts
src/mixins/createParentMapMixin.ts
src/mixins/createRenderableChildrenMixin.ts
src/mixins/createStatefulChildrenMixin.ts
src/mixins/createTabbedMixin.ts
src/mixins/interfaces.ts
src/util/lang.ts
src/util/query.ts
tests/unit/createContainer.ts
tests/unit/integrations.ts
tests/unit/mixins/createParentListMixin.ts
tests/unit/mixins/createParentMapMixin.ts
tests/unit/mixins/createRenderableChildrenMixin.ts
tests/unit/mixins/createStatefulChildrenMixin.ts
tests/unit/mixins/createTabbedMixin.ts
tests/unit/util/lang.ts

Remove dependency on `immutable` within `widgets`
Resolves #123

Remove dep on immutable

---

package.json

**Type:** bug
Need to pin the version of stores.

pin stores version

---

README.md

Documentation on how to use `dojo-widgets`
Resolves #130

README documentation.

---

src/components/button/createButton.ts
src/components/textinput/createTextInput.ts
src/createProjector.ts
src/createWidgetBase.ts
src/d.ts
src/mixins/createCssTransitionMixin.ts
src/mixins/createFormFieldMixin.ts
src/mixins/createVNodeEvented.ts
tests/unit/createWidgetBase.ts
tests/unit/d.ts

Update all references of `widgetBases` to use the local `interfaces`

update all references to local interfaces

---

Gruntfile.js

**Type:** bug
Do not need any custom grunt config anymore.
Resolves #164

clean up grunt file

---

README.md

Enhance the widgets readme
Resolves #142
[skip ci]

Add more README details

---

README.md

**Type:** bug
Fixes the README

Fix name of registry in widget README

---

README.md

**Type:** bug
Update README to show correct usage of load when using a registry

Update README to show correct usage of load when using a registry

---

src/interfaces.d.ts

**Type:** bug 
Remove unused interfaces.
Resolves #167

Remove unused interfaces

---

README.md

Add key widgets principles to readme

Add widgets principles to readme

---

src/mixins/shallowPropertyComparisonMixin.ts
tests/unit/mixins/shallowPropertyComparisonMixin.ts

only compare arrays to arrays, objects to objects and short circuit on array length.

Fixed missing comparison logic

---

src/createWidgetBase.ts
src/interfaces.d.ts
src/mixins/shallowPropertyComparisonMixin.ts
tests/intern-saucelabs.ts
tests/unit/createWidgetBase.ts
tests/unit/d.ts

Update `createWidgetBase` and related friends to use the latest changes to dojo-interfaces and dojo-compose.
Waiting on https://github.com/dojo/interfaces/pull/57 & https://github.com/dojo/compose/pull/113
Related to https://github.com/dojo/compose/issues/112

Enhancement: Update to latest dojo-interfaces and dojo-compose

---

package.json
tests/intern.ts

**Type:** bug
Remove `cldr-data` and `globalize` from the dependencies list in `package.json`.
Resolves #203

Remove `cldr-data` and `globalize` as dependencies

---

src/components/button/createButton.ts
tests/unit/createWidgetBase.ts

Fix typings for test

---

src/mixins/externalState.ts
tests/unit/mixins/externalState.ts

**Type:** bug
ensure external state is initialised correctly
Resolves #228

initialise the external state on instantiation

---

src/interfaces.d.ts

Add index type to WidgetProperties
Resolves #233

Add index type to WidgetProperties

---

README.md

**Type:** bug
Resolves dojo/meta#135

Updated readme with new npm version badge [skip ci]

---

README.md
package.json

Update the readme in line with the latest code changes. This is by no means fully finalised but is more accurate/up to date than the existing readme.
Easier to review using https://github.com/agubler/widgets/blob/new-readme/README.md

Widgets README update

---

src/createWidgetBase.ts
src/interfaces.d.ts
src/mixins/registryMixin.ts
tests/unit/createWidgetBase.ts
tests/unit/mixins/all.ts
tests/unit/mixins/externalState.ts
tests/unit/mixins/registryMixin.ts

Registry Mixin

---

tests/intern.ts

Remove rxjs, immutable from intern.ts, fixes #294

---

src/createWidgetBase.ts
src/interfaces.d.ts

Add `render` to the widget base public API
Resolves #304

add 'render' public function to base API

---

src/createWidgetBase.ts
src/d.ts
src/interfaces.d.ts
tests/unit/d.ts

Generic decorator for DNodes.
Resolves #302

Generic DNode decorator util

---

src/mixins/createFormLabelMixin.ts

**Type:** bug
Missed a factory

Add missing form label mixin factory

---

README.md

README changes for `render` and removal of `nodeAttributes`

---

package.json
tests/functional/support/registerCustomElement.html

Removing external references to web component shims in the functional tests.

Removing external URLs and adding webcomponents dev dep

---

README.md

Updating the README for custom elements. There was some important pieces missing!

Updating README to include more information on custom elements

---

src/mixins/Themeable.ts
tests/unit/mixins/Themeable.ts

Re-raising because I am an idiot and nuked the previous merge by doing a force push to master...
classes and chained fixed functions can now accept null as a class.
Resolves #336

Added filter for null classes

---

src/animations/cssTransitions.ts

**Type:** bug
This interface needs to be exported for a `grunt dist` on widget-core..

Exporting interface for css transitions

---

README.md

Updated README to reflect the change to classes
Resolves #335

Update readme to reflect changes to classes

---

src/customElements.ts
src/mixins/Projector.ts
tests/unit/mixins/Projector.ts

Add `root` as a parameter for `append`/`replace` and `merge`
Resolves #338

Accept root as an option for append/merge/replace

---

src/WidgetBase.ts
src/bases/Destroyable.ts
src/bases/Evented.ts
src/mixins/FormLabel.ts
src/mixins/I18n.ts
src/mixins/Projector.ts
src/mixins/Registry.ts
src/mixins/Stateful.ts
src/mixins/Themeable.ts
src/util/DomWrapper.ts

**Type:** discussion
Add module default exports where sensible.

Return of the default exports

---

src/mixins/Themeable.ts

Move ThemeableMixin utility functions outside of class

---

src/FactoryRegistry.ts
src/WidgetBase.ts
src/bases/Destroyable.ts
src/bases/Evented.ts
src/d.ts
src/mixins/I18n.ts
src/mixins/Projector.ts
src/mixins/Stateful.ts
src/mixins/Themeable.ts

**Type:** bug
Spelling mistakes

Correct documentation typos

---

README.md

Update readme to reference VirtualDomProperties

---

tests/unit/WidgetBase.ts
tests/unit/mixins/Themeable.ts

Improves unit tests within `WidgetBase` and `Themeable` to cover scenarios that would have failed for the bugged changes in #372

Improve unit test coverage

---

package.json

Resolves https://github.com/dojo/meta/issues/152

Bump TS up to 2.2.1

---

src/WidgetBase.ts
tests/unit/WidgetBase.ts

Fix for confusing class decorators
Resolves #395

Changing the way decorators are stored

---

src/WidgetBase.ts
src/interfaces.d.ts
src/mixins/FormLabel.ts
src/mixins/I18n.ts
src/mixins/Projector.ts
src/mixins/Stateful.ts
src/mixins/Themeable.ts
src/util/DomWrapper.ts
tests/unit/WidgetBase.ts
tests/unit/util/DomWrapper.ts

Update private variables prefixed with `_` and update visibility for class method/properties.
Resolves #388

Private variables and visibility clean up

---

package.json

**Type:** enhancement
Updates the `@dojo/core` peer dependency to alpha.26.
Resolves #???

Update @dojo/core to alpha.26

---

package.json

Added min npm version to package.json

---

src/WidgetBase.ts
tests/unit/WidgetBase.ts

add beforeRender decorator

---

src/Injector.ts
src/WidgetBase.ts
src/mixins/Container.ts
tests/intern-saucelabs.ts
tests/unit/Injector.ts
tests/unit/WidgetBase.ts
tests/unit/all.ts
tests/unit/mixins/Container.ts
tests/unit/mixins/all.ts

Implement the base classes required to support injecting context using the concept of an "Injector" to define the context and a "Container" to wrap a Widget and provide the bindings between the context and the component.
Resolves #440

Enhancement: State Injection using Container and Injector Pattern

---

.travis.yml
tests/intern-local.ts
tests/intern.ts

Switches to BrowserStack JS Foundation team for CI testing with Travis.

Switch to BrowserStack for CI

---

package.json
tests/functional/registerCustomElement.ts

**Type:** bug
Taking @rorticus's changes and adding skip of iOS 9.1 platform for functionals.
Resolves #477

Increase polyfil version, increase timeout and skip for ios9

---

README.md

ThemeableMixinProperties is ThemeableProperties

---

src/customElements.ts
src/util/DomWrapper.ts
tests/unit/util/DomWrapper.ts

Resolves https://github.com/dojo/widget-core/issues/518

Allow property passing to DomWrapper

---

src/Container.ts

Export type for `Container`
Resolves #550

export Container type

---

tests/unit/mixins/Projector.ts

**Type:** bug
Failing lint errors

lint errors

---

src/diff.ts
tests/unit/diff.ts

Auto diff widget constructor

---

package.json
src/Container.ts
src/Injector.ts
src/RegistryHandler.ts
src/WidgetBase.ts
src/WidgetRegistry.ts
src/customElements.ts
src/d.ts
src/interfaces.d.ts
src/mixins/I18n.ts
src/mixins/Projector.ts
src/mixins/Registry.ts
src/mixins/Stateful.ts
src/mixins/Themeable.ts
src/registerCustomElement.ts
src/util/DomWrapper.ts
tests/unit/WidgetBase.ts
tests/unit/lifecycle.ts
tests/unit/mixins/Projector.ts

**Type:** bug
General clean up in the codebase, includes making `invalidate` protected.

General clean up, spelling, import order, visibility etc

---

README.md

**Type:** documentation
Resolves #545 
[ci skip]

Add DomWrapper to README

---

src/Injector.ts
src/WidgetBase.ts
src/interfaces.d.ts
tests/unit/WidgetBase.ts
tests/unit/WidgetRegistry.ts
tests/unit/testIntegration.tsx

Upgrading to TS.2.4
Requires 2.4 to be released.

Forward Compatibility for TS2.4 Release

---

README.md

Resolves https://github.com/dojo/widget-core/issues/593

README: Decorators not called

---

tests/support/util.ts
tests/unit/RegistryHandler.ts

**Type:** bug
Fix compile errors from dep version upgrades.

Fix compile errors from latest dependencies

---

src/mixins/Themeable.ts
tests/unit/mixins/Themeable.ts

Filter all `falsy` values passed to `this.classes`
Resolves #592

Filter all `falsy` values from 'this.classes'

---

.travis.yml

Run `grunt dist` as part of CI

Add grunt dist to travis.yml

---

src/WidgetBase.ts

**Type:** bug
Through a series of unfortunate merges we have ended up with a lint'ing failure.

Remove unused import

---

package-lock.json
src/WidgetBase.ts
tests/unit/WidgetBase.ts

**Type:** bug
Do not overwrite the `coreProperties` once they have been set.
Resolves #723

Ensure the functions are bound to the parent widget not containing widget

---

intern.json
package-lock.json
package.json
src/vdom.ts
tests/unit/meta/Dimensions.ts
tests/unit/vdom.ts

**Type:** bug
* Support adding and removing multiple classes in IE11
* Add IE11 to browserstack configuration.
* Added two other fixes for tests in IE11
Resolves https://github.com/dojo/widgets/issues/367

Support Adding and Removing Multiple class in IE11

---

src/WidgetBase.ts

Convert non critical resources to instantiate lazily when required.
Related to #760

Convert WidgetBase to create resources lazily

---

package-lock.json
package.json

Upgrade dojo dependencies

---

src/mixins/Themed.ts
tests/unit/mixins/Themed.ts

Fix base theme classes to override correctly

---

README.md

**Type:** bug
This adds information about the `Drag` meta provider.
Partially resolves #780 
[ci skip]

Add Drag meta provider to README

---

README.md

Adds details for the `meta` and `nodehandler` changes to the readme file.
Resolves #677

677 - Update meta details in readme

---

README.md

Probably not a good idea to link anybody to that page.

Remove api doc link

---

src/WidgetBase.ts
src/animations/cssTransitions.ts
src/customElements.ts
src/d.ts
src/interfaces.d.ts
src/mixins/I18n.ts
src/tsx.ts
src/util/DomWrapper.ts
src/vdom.ts
tests/unit/WidgetBase.ts
tests/unit/customElements.ts
tests/unit/d.ts
tests/unit/mixins/Projector.ts
tests/unit/tsx.ts
tests/unit/vdom.ts

Updates `HNode` to `VNode` and `VirtualDomProperties` to `VNodeProperties`.
Resolves #797

Change HNode to VNode and VirtualDomProperties to VNodeProperties

---

README.md

Adds description / example of registry dealing with esModules to readme
Resolves #810

Add details of registry esmodules handling to readme

---

README.md

Tidy up registry readme examples

---

package.json

Removes the dojo/interfaces dependency 
Resolves https://github.com/dojo/meta/issues/223

Remove the dojo/interfaces dep

---

package-lock.json
package.json

**Type:** bug
Refs https://github.com/dojo/meta/issues/226

Move tslib from dev dep to dep

---

README.md
package-lock.json
package.json
src/meta/Base.ts
src/meta/Focus.ts
tests/support/loadJsdom.ts
tests/support/util.ts
tests/unit/customElements.ts
tests/unit/meta/Focus.ts
tests/unit/meta/Intersection.ts
tests/unit/meta/WebAnimation.ts
tests/unit/meta/all.ts
tests/unit/vdom.ts

Addresses #729. Creates Focus meta that provides information about whether a node is currently focused or contains focus.
Updates sinon to ^4.1.3, along with syntax updates in any tests that required it.

Focus meta provider

---

src/interfaces.d.ts

Revert "Add typings for `styles` on `VNodeProperties`"

---

src/mixins/I18n.ts

**Type:** bug
Do not import from main, ever.

Do not import from main

---

package-lock.json
src/vdom.ts
tests/unit/vdom.ts

**Type:** bug 
Ensure that TextNodes are removed and appended correctly when passing a text node to `dom()`
Resolves #870

Ensure that when TextNodes are passed to 'dom()' they are added and removed correctly

---

package-lock.json
package.json
src/meta/WebAnimation.ts

Dependent on `@dojo/shim` changes
Resolves #770 
Shim pr: https://github.com/dojo/shim/pull/132

Remove web-animations polyfill dependency and import

---

README.md

Minor readme grammar cleanup [ci skip]

---

intern.json
package-lock.json
src/meta/Intersection.ts
src/mixins/Projector.ts
tests/functional/meta/Drag.html

**Type:** bug
This dependency is handled by @dojo/shim/browser

Remove pepjs, handled by dojo/shim/browser

---

README.md
package-lock.json
src/mixins/I18n.ts
tests/unit/mixins/I18n.ts

**Type:** bug
Updates the `localizeBundle` method in `src/mixins/I18n` to return a blank locale bundle while waiting for locale-specific messages to load. If `true` is passed as the second argument, the default messages will be returned instead of a blank bundle. The returned object also now has an `isPlaceholder` property, which indicates whether the returned messages are just the (blank or default) placeholders or the actual locale-specific messages.
```
const bundle = {
locales: {
es: () => {
greeting: '¡Hola, {name} Mundo!'
}
},
messages: {
greeting: 'Hello, {name} World!'
}
};
export MyWidget extends I18nMixin(WidgetBase) {
render() {
// Current behavior: return the default messages when localized bundle has
// not yet …
```

I18nMixin: return blank locale bundle by default

---

package-lock.json
package.json
src/Injector.ts
src/NodeHandler.ts
src/Registry.ts
src/RegistryHandler.ts
src/WidgetBase.ts
src/meta/Base.ts
src/meta/Focus.ts
src/meta/WebAnimation.ts
src/mixins/I18n.ts
src/mixins/Projector.ts
src/mixins/Themed.ts
src/tsx.ts
tests/benchmark/runner/src/benchmarks.ts
tests/unit/d.ts
tests/unit/vdom.ts

Forwards compatibility for TS2.7 and upgrade @dojo/core.
Requires release and update of the dojo/i18n version

TS2.7 forwards compatibility

---

src/WidgetBase.ts
tests/unit/decorators/diffProperty.ts

Pass all the previous and current properties to diff property reactions
Resolves #936

Pass all the properties, previous and current to diff property reactions

---

README.md

Minor grammar fixes to recent focus readme additions.

Grammar fixes to focus readme
