- src/projector.ts
- tests/support/loadJsdom.ts
See commits.
TL;DR this allows the projector to be required from Node.js runtimes that haven't polyfilled the `document` global, perhaps because they don't need the projector but cannot avoid requiring it.
> Allow projector module to be loaded in non-browser environments

- src/projector.ts
- tests/unit/projector.ts
See usage in <https://github.com/dojo/app/pull/5/commits/8181b989d6194588c9ee5d6b46859b84a3cfe2e9>.
When the promise fulfils you know the projector has actually been attached to the DOM. Previously it would return a handle but attach asynchronously.
You can specify an `afterCreate` callback which is called synchronously after the projector has been attached, allowing you to make further changes before the DOM is painted.
> Return a promise from Projector#attach(), support afterCreate option

- src/mixins/createCachedRenderMixin.ts
- src/mixins/createRenderableChildrenMixin.ts
- src/mixins/createTabbedMixin.ts
- src/mixins/interfaces.d.ts
- tests/unit/mixins/createTabbedMixin.ts
This PR refactors `TabbedMixin` to utilise the `ParentMap` mixin instead of the `ParentList` mixin.  This allows tabs to be referenced by name instead of by index, as well as there is ability to change the sort order of the tabs based on a custom sort function.
> Refactor TabbedMixin to be ParentMap instead of ParentList

- src/mixins/createStatefulChildrenMixin.ts
- tests/unit/mixins/createStatefulChildrenMixin.ts
> Full test coverage of StatefulChildrenMixin, guard against race condition

- src/examples/index.ts
- src/mixins/createStatefulChildrenMixin.ts
- src/mixins/createStatefulListenersMixin.ts
- src/mixins/interfaces.ts
- tests/unit/mixins/createStatefulChildrenMixin.ts
- tests/unit/mixins/createStatefulListenersMixin.ts
Rather than creating widgets with a particular registry, expect a registry provider to be passed. Widgets can access the required registry via this provider.
See also <https://github.com/dojo/app/pull/18>.
> Expect a registry provider to provide a registry

- src/util/createMemoryStore.ts
- tests/unit/util/createMemoryStore.ts
This PR changes the behaviour of `.patch()` so that if the ID is missing, it will add the object to store instead of rejecting as previous.
Fixes #26
> MemoryStore patch with missing ID adds instead of rejects

- src/examples/index.ts
- src/mixins/createStatefulChildrenMixin.ts
- src/mixins/interfaces.ts
- tests/unit/mixins/createStatefulChildrenMixin.ts
- tests/unit/mixins/createStatefulListenersMixin.ts
This PR allows instances of `createStatefulChildrenMixin` to be able to create children that are intended to be managed externally (like via `dojo/app`).  Specifically it assumes that `widget` registries return not only contain `get` and `identify` but also `create()` with the signature of:
```typescript
export interface CreatableRegistry<T extends Child> extends Registry<T> {
/**
* Realize a child of the specified parent, returning a promise which resolves with
* a tuple that contains the ID and the realized instance.
*
* @param parent The parent where the realized child should be attached to
* @param factory The factory that should be used to realize the child
* @param options Any options that should be passed to the factory when realizing the child
*/
create<U extends T, O>(parent: { …
```
> Add createChild() to createStatefulChildrenMixin

- src/mixins/createStatefulChildrenMixin.ts
This is a minor PR that improves upon #23 and is related to #24 which creates an new interface in `createStatefulChildrenMixin` which allows consumers of the model to better describe the return results from `.createChildren()`
> Improve interfaces for createStatefulChildrenMixin

- src/mixins/createFormFieldMixin.ts
- tests/unit/createButton.ts
- tests/unit/mixins/createFormFieldMixin.ts
**Type:** bug
Lint error reporting `disabled` attribute of `VNodeProperties` is typed as `boolean` not string.
Lint Error: `src/mixins/createFormFieldMixin.ts(120,6): error TS2322: Type 'string' is not assignable to type 'boolean'.`
> VNodeProperties disabled attribute is typed as boolean

- src/mixins/createCssTransitionMixin.ts
- src/projector.ts
- tests/unit/mixins/all.ts
- tests/unit/mixins/createCssTransitionMixin.ts
- tests/unit/projector.ts
Widget mixin to support CSS transitions within the widget architecture.
Using css transitions with Maquette requires loading Maquette's provided `css-transitions.js` in the page, this is then used within the Maquette projector construction assuming the `cssTransitions` options has been set to `true`.
Currently due to limitations in the provided `css-transitions.js` script, `exitAnimation` is only supported for CSS Transitions and not CSS Animations (like those provided by `animate.css`), currently the element is not being correctly removed from the DOM on completion of the exitAnimation.
Related to #56
> Feature: Support CSS Transitions with Maquette Projector and Widget Mixin

- src/mixins/createFormFieldMixin.ts
- src/mixins/createRenderMixin.ts
- src/projector.ts
In the latest release of Maquette all the properties of `VNodeProperties` are marked as `readonly` - these changes prevent the regressions noted in issue #62.
We could also maintain a local interface the represents `VNodeProperties` but that might become a pain to maintain (although I added a partial interface for the `projector`, so am open to all suggestions)
resolves #62
> Work around VNodeProperties attributes being marked as readonly

- package.json
- src/createDijit.ts
- src/createResizePanel.ts
- src/examples/index.ts
- src/examples/scratch.ts
- src/mixins/createFormFieldMixin.ts
- src/mixins/createParentListMixin.ts
- src/mixins/createParentMapMixin.ts
- src/mixins/createRenderMixin.ts
- src/mixins/createRenderableChildrenMixin.ts
- src/mixins/createStatefulChildrenMixin.ts
- src/mixins/createStatefulListenersMixin.ts
- src/mixins/createTabbedMixin.ts
- src/mixins/createVNodeEvented.ts
- src/projector.ts
- src/util/lang.ts
- tests/intern.ts
- tests/support/dijit/Dijit.ts
- tests/unit/createButton.ts
- tests/unit/createContainer.ts
- tests/unit/createDijit.ts
- tests/unit/createList.ts
- tests/unit/mixins/createListMixin.ts
- tests/unit/mixins/createRenderMixin.ts
- tests/unit/mixins/createStatefulChildrenMixin.ts
- tests/unit/mixins/createStatefulListenersMixin.ts
- tests/unit/mixins/createTabbedMixin.ts
- tests/unit/mixins/createVNodeEvented.ts
- tsconfig.json
Enables strict null checks and fixes violations. Some changes impact exported typings but I don't think it breaks behavior for consuming libraries that have not yet enabled strict null checks.
Depends on <https://github.com/dojo/shim/pull/19> and <https://github.com/dojo/core/pull/194> being on npm.
> Enable strict null checks

- src/mixins/createStatefulChildrenMixin.ts
- tests/unit/mixins/createStatefulChildrenMixin.ts
**Type:** bug
When two identical updates to `state.children` occur sequentially it is possible for the first update to be invalidated due to a "later state change" but the "later state change" fall into the short circuit return, that checks whether the `children` of the internalState and the current widget `state` match.
The generation increment should occur after the check against the known state of the children.
Resolves #78
> Move 'generation' increment to after the 'state.children' check

- src/examples/index.ts
- src/mixins/createStatefulChildrenMixin.ts
- src/mixins/interfaces.ts
- tests/support/mockRegistryProvider.ts
- tests/unit/mixins/createStatefulChildrenMixin.ts
**Type:** bug
Attempt to handle stale (destroyed) widget's ids being set on the children array in parent's state, this occurs when multiple children are destroyed asynchronously. Which calls `setState` on the parent widget to reconcile the children state, but by the time the `manageChildren` function is exec's some or all of the remaining children from the `setState` have also be destroyed.
Resolves #75 
Depends on `has` being exposed from the widget registry in `app` (https://github.com/dojo/app/pull/79)
> Ensure destroyed widgets are not added to the a parent

- src/util/d.ts
Type `d` to allow `null` entries in children.
Resolves #93
Depends on a release of dojo-interfaces containing https://github.com/dojo/interfaces/pull/33
> type 'd' to allow children with null entries

- tslint.json
**Type:** bug
* [X ] There is a related issue
* [ X] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
Remove 'no-duplicate-key' entry from tslint.json
Resolves dojo/meta#90
> remove 'no-duplicate-key' from tslint.json, refs dojo/meta#90

- package.json
**Type:** bug
Used `~` instead of `^` to stop typescript 2.1 being installed
Resolves https://github.com/dojo/widgets/issues/97
> Use ~ instead of ^ for typescript version

- src/bases/createWidgetBase.ts
- src/mixins/createParentListMixin.ts
- src/mixins/createParentMapMixin.ts
- tests/unit/bases/createWidgetBase.ts
Renames the `WidgetBase` event type `invalidate` to `invalidated`.
Resolves #100
> Change WidgetBase event type 'invalidate' to 'invalidated'

- src/util/d.ts
- tests/unit/bases/createWidgetBase.ts
- tests/unit/util/d.ts
Add generics for `d` that extend `Widget`, `WidgetState` and `WidgetOptions`
> add generic types for 'd'

- package.json
- src/createButton.ts
- src/createContainer.ts
- src/createDijit.ts
- src/createLayoutContainer.ts
- src/createList.ts
- src/createPanel.ts
- src/createTabbedPanel.ts
- src/createTextInput.ts
- src/mixins/createListMixin.ts
- src/mixins/createTabbedMixin.ts
- tests/functional/tabbedPanel.ts
- tests/unit/bases/createWidgetBase.ts
- tests/unit/mixins/createStatefulChildrenMixin.ts
- tests/unit/projector.ts
Remove references to `compose.extend` and replace with `.override` or `.mixin`
Also pin `intern` to version `3.3.2`
Resolves #112
> Replace references to `extend` with `mixin` or `override`

- package.json
- typings.json
Using the latest release of intern `3.4.1` and remove explicit types from `package.json`
> Use latest intern release (^3.4.1)

- src/util/d.ts
- tests/unit/bases/createWidgetBase.ts
- tests/unit/util/d.ts
Resolves #114 
Support children as the second param when using `d` to generate a ` HNode`
> support 'children' as the second argument when creating HNodes

- src/bases/createWidgetBase.ts
- tests/unit/bases/createWidgetBase.ts
- tests/unit/util/d.ts
Support being able to pass a `string` as a child which will get passed to maquette to use a text node.
Resolves #118 
Depends on https://github.com/dojo/interfaces/pull/40
> Support creating text nodes for children

- src/bases/createWidgetBase.ts
- tests/unit/bases/createWidgetBase.ts
Move to a single function to provide children for a widget.
Resolves #131
> Expose a single getChildrenNodes function

- Gruntfile.js
- package.json
- typings.json
**Type:** bug
Fix typings when using intern `3.4.1` - was failing whilst running `grunt dist`
> fix typings for intern '3.4.1'

- src/interfaces.d.ts
Moves widget bases from `dojo-interfaces` 
Resolves #https://github.com/dojo/interfaces/issues/41
> Move widgetBases from dojo-interfaces into widgets

- src/createProjector.ts
- src/createWidgetBase.ts
- src/interfaces.d.ts
- tests/unit/components/button/createButton.ts
- tests/unit/createProjector.ts
- tests/unit/createWidgetBase.ts
Implement `getNode` that returns the top level node for a widget and called by `render`
Resolves #144
Depends on: https://github.com/dojo/interfaces/pull/46
> Expose top level getNode function

- src/createWidgetBase.ts
- src/d.ts
- src/interfaces.d.ts
- tests/unit/createWidgetBase.ts
- tests/unit/d.ts
Add support in `d` and `createWidgetBase` for passing `children` to when creating a widget using a factory.
Resolves #145
Depends on https://github.com/dojo/interfaces/pull/47
> Support children for widgets

- src/createProjector.ts
- tests/unit/createProjector.ts
Add attach type as an option for `projector.attach(...)`
Resolves #150
> Add attach type for projector

- src/components/button/createButton.ts
- src/components/textinput/createTextInput.ts
- src/createWidgetBase.ts
- tests/unit/createWidgetBase.ts
Add `VNodeEvented` to `createWidgetBase` by default.
Resolves #115
> include VNodeEvented in Widget base

- src/createWidgetBase.ts
- src/interfaces.d.ts
- tests/unit/createProjector.ts
- tests/unit/createWidgetBase.ts
With the `children` API `getChildrenNodes` is not required to be available as an option to pass on instantiation.
Resolves #153
> remove 'getChildrenNodes' from WidgetOptions

- src/createProjector.ts
- src/createWidgetBase.ts
- tests/unit/createProjector.ts
- tests/unit/createWidgetBase.ts
Invalidate the `projector` when children are set.
Resolves #155
> Invalidate projector on setting children

- package.json
**Type:** bug
`dojo-stores` is no longer a peer dependency.
Resolves #159
> remove dojo-stores as a peer dep

- README.md
- src/FactoryRegistry.ts
- src/createProjector.ts
- src/createWidgetBase.ts
- src/d.ts
- src/interfaces.d.ts
- tests/unit/FactoryRegistry.ts
- tests/unit/all.ts
- tests/unit/createProjector.ts
- tests/unit/createWidgetBase.ts
- tests/unit/d.ts
As per the issue, implement `FactoryRegistry` to enable support for lazily loading factories during the render.
Resolves #165
> Impement Factory Registry

- README.md
- src/createWidgetBase.ts
- src/d.ts
- src/interfaces.d.ts
- tests/unit/createWidgetBase.ts
Automatically pass the widget instance to `h`, this becomes the value of `this` for all event handlers.
Resolves #168
> Pass widget instance as `bind` attribute when `h` is called

- package.json
- tests/unit/integrations.ts
**Description:** 
Update `typescript` dependency to `~2.1.4`
**Reference Issue:** #https://github.com/dojo/meta/issues/124
> update typescript to ~2.1.4

- src/createProjector.ts
- src/createWidgetBase.ts
- src/interfaces.d.ts
- tests/unit/components/button/createButton.ts
- tests/unit/createProjector.ts
- tests/unit/createWidgetBase.ts
**Type:** bug
Rename `createWidgetBase.render` to `createWidgetBase.__render__` 
Resolves #179
> rename 'render' to '__render__'

- README.md
- package.json
- src/components/button/createButton.ts
- src/components/textinput/createTextInput.ts
- src/createProjector.ts
- src/createWidgetBase.ts
- src/d.ts
- src/interfaces.d.ts
- src/mixins/createCssTransitionMixin.ts
- src/mixins/createFormFieldMixin.ts
- tests/unit/components/button/createButton.ts
- tests/unit/createWidgetBase.ts
- tests/unit/d.ts
- tests/unit/integrations.ts
- tests/unit/mixins/createCssTransitionMixin.ts
- tests/unit/mixins/createFormFieldMixin.ts
- typings.json
Support properties that can be passed to widgets that will be used to internally update state on the widget.
By default only new or updated properties will be used to update state automatically. The functions are public and can be customised by a widget consumer if they require different equality checks for current and previous properties or need to perform some mapping or logic to from the properties to the internal state.
Will be dependant on interfaces/compose changes.
Resolves #176
> Support properties to update internal state

- src/createWidgetBase.ts
- tests/unit/createWidgetBase.ts
**Type:** bug(s)
Ensure properties are "reset" by `deepAssign`ing them before setting them on internal state and use `hasOwnProperty` to check if a `key` exists on the `previousProperties`
Resolves #188 
Resolves #189
> Use `hasOwnProperty` to check for key and `deepAssign` properties for internal state.

- src/components/button/createButton.ts
- tests/unit/components/button/createButton.ts
**Type:** bug
A label on a button is not mandatory.
> A label is not mandatory for a button

- src/createWidgetBase.ts
- src/mixins/shallowPropertyComparisonMixin.ts
- tests/unit/createWidgetBase.ts
- tests/unit/mixins/all.ts
- tests/unit/mixins/shallowPropertyComparisonMixin.ts
Provide a `mixin` that overrides the `diffProperties` function providing an enhanced algorithm to perform a "shallow" comparison for Array and Object attributes passed as `WidgetProperties`.
For Objects, `values` for all keys are compared against the equivalent key on the `previousProperties` attribute using `===`. If the key does not exists on the `previousProperties` attribute it is considered unequal.
For Arrays, each item is compared with the item in the equivalent index of the `previousProperties` attribute. If the item is an object then the object comparison described above is applied otherwise a simple `===` is used.
Usage:
```ts
const createMyCustomWidget = …
```
> Shallow Property Comparison Mixin

- package.json
- src/createWidgetBase.ts
- src/interfaces.d.ts
- src/mixins/shallowPropertyComparisonMixin.ts
- tests/unit/createWidgetBase.ts
- tests/unit/mixins/shallowPropertyComparisonMixin.ts
Resolves #207, #202 
This refines the property lifecycle for widgets. The lifecycle is itself now triggered by a `setProperties` call rather than the `__render__` call.
The new lifecycle is as follows:
```ts
diffProperties(previousProperties: P, newProperties: P): string[];
assignProperties(previousProperties: P, newProperties: P, changedPropertyKeys: string[]): P;
```
`diffProperties` is responsible for diffing the previous and new properties - returning an array of property keys that have changed.
`assignProperties` returns a set of properties to be assigned to `this.properties` for usage later.
If `diffProperties` returns an array of length > 0 an event of `properties:changed` is triggered, as well as …
> Refine properties lifecycle, add public setProperties()

- src/createWidgetBase.ts
- src/mixins/shallowPropertyComparisonMixin.ts
- tests/unit/createWidgetBase.ts
- tests/unit/mixins/shallowPropertyComparisonMixin.ts
**Type:** bug
Move the property function type check to `onPropertiesChanged` instead of in the `diffProperties` implementation in `shallowPropertyComparisonMixin`.
Resolves #216
> Move the function type check of properties to onPropertiesChanged

- package.json
- src/mixins/externalState.ts
- tests/intern.ts
- tests/unit/mixins/all.ts
- tests/unit/mixins/externalState.ts
Adds a mixin to support backing widgets with external state.
Resolves #205
> Enhancement: External State Mixin

- src/FactoryRegistry.ts
- src/components/button/createButton.ts
- src/components/textinput/createTextInput.ts
- src/createWidgetBase.ts
- src/d.ts
- src/interfaces.d.ts
- src/mixins/createI18nMixin.ts
- src/mixins/createProjectorMixin.ts
- tests/unit/components/button/createButton.ts
- tests/unit/components/textinput/createTextInput.ts
Abstract the details of `ComposeFactory`, `WidgetState` and `WidgetOptions` from consumers and widget authors, leaving `WidgetProperties` that should be used to provide a widgets public API.
Additionally a convenience interface `WidgetFactory` is now available from `src/interfaces` that abstracts `WidgetOptions` and `WidgetState` from consumers and should be preferred over using `ComposeFactory`. This also means widget authors will not need to import anything from `dojo-compose` in there code and hopefully will remove potential confusion. 
Resolves #229
> Update the public widget api to require only WidgetProperties

- src/interfaces.d.ts
**Type:** bug
Remove incorrect attribute typing (`preventDefaultBind`) from `WidgetProperties`
> remove incorrect widget property

- src/interfaces.d.ts
**Type:** bug
Attributes should be able to be defined as mandatory for `WidgetProperties`
> Allow non optional properties

- src/createWidgetBase.ts
- src/interfaces.d.ts
- src/mixins/externalState.ts
**Type:** bug
Make `properties` on `WidgetMixin` `readonly`
Resolves #238
> make properties attribute readonly

- src/createWidgetBase.ts
- src/interfaces.d.ts
- src/mixins/shallowPropertyComparisonMixin.ts
- tests/unit/createWidgetBase.ts
- tests/unit/mixins/shallowPropertyComparisonMixin.ts
Combine the existing `diffProperties` and `assignProperties` into a single `diffProperties`
Resolves #247
> Combine diffProperties and assignProperties API

- src/createWidgetBase.ts
- src/interfaces.d.ts
- src/mixins/shallowPropertyComparisonMixin.ts
- tests/unit/createWidgetBase.ts
- tests/unit/mixins/shallowPropertyComparisonMixin.ts
Expose an API to allow consumers to apply property specific `diff` functionality.
Resolves #248
> Diff Individual Property API

- src/createWidgetBase.ts
- src/d.ts
- src/interfaces.d.ts
- tests/unit/d.ts
Add type to `HNode` and `WNode` and helper `isWNode` and `isHNode` functions.
Resolves #236
> Add symbol type to WNode and HNode

- src/createWidgetBase.ts
- src/interfaces.d.ts
- tests/unit/createWidgetBase.ts
- tests/unit/mixins/createProjectorMixin.ts
**Type:** bug
Make `children` `readonly`
Resolves #254
> children should be readonly

- src/createWidgetBase.ts
- tests/unit/createWidgetBase.ts
- tests/unit/mixins/shallowPropertyComparisonMixin.ts
Provide default shallow property diffProperties
Resolves #214
> Provide default shallow property `diffProperties`

- src/components/button/createButton.ts
- src/createWidgetBase.ts
- src/interfaces.d.ts
- src/mixins/createI18nMixin.ts
- src/mixins/createProjectorMixin.ts
- src/mixins/internalState.ts
- tests/unit/components/button/createButton.ts
- tests/unit/createWidgetBase.ts
- tests/unit/mixins/all.ts
- tests/unit/mixins/internalState.ts
Split the default stateful behaviour from `createWidgetBase` into a mixin - `internalState`. 
This changed also removes the `createWidgetBase#onPropertiesChanged` API  that was previously wired to the `properties:changed` event and coverts all references of `state` to `properties`. 
By default `createWidgetBase` now wires `createWidgetBase#invalidate` to the event.
Resolves #213
> Internal state mixin

- src/interfaces.d.ts
**Type:** bug
Ensure that `properties` are readonly.
Resolves #238
> Use mapped type to ensure the properties object is readonly

- src/createWidgetBase.ts
- tests/unit/createWidgetBase.ts
An alternative to #278 based on suggestions from @matt-gadd.
As per the associated issue, support factory changing for a child with an id and intelligently cache child widgets using the same factory without an explicit id.
Resolves #276
> Improve `createWidgetBase` internal instance cache

- src/interfaces.d.ts
**Type:** bug
Allow mandatory properties
> Partial P for return of diff properties to allow Mandatory properties

- src/createWidgetBase.ts
- src/interfaces.d.ts
- tests/unit/createWidgetBase.ts
`id` is overloaded and therefore a key might be required for a widget but not be the `id` of the widget which could cause issues. Also aligns with Maquette's terminology.
Resolves #288
> Use 'key' for instance management instead of 'id'

- src/mixins/storeMixin.ts
- tests/unit/mixins/storeMixin.ts
**Type:** bug
Add store data to data property on state rather than replacing state.
Resolves #284
> Add store data to data property on state when observing a store without an id

- src/mixins/storeMixin.ts
- tests/unit/mixins/storeMixin.ts
Calls `widget.invalidate()` on the `state:changed` event
Resolves #285
> Call invalidate on state change in store mixin

- src/mixins/themeable.ts
**Type:** bug
- Make applied classes keys non-optional
- Change all generics to `<T>` (for Theme) and remove / fix incorrect generics
- Change factory generic from `<{}>` to `<any>` as we do know know until it is initialized / used what the type will be.
Resolves #291
> Fix generics for the themeable mixin and make applied classes keys non-optional

- README.md
- src/customElements.ts
- src/util/createDomWrapper.ts
- tests/unit/all.ts
- tests/unit/customElements.ts
- tests/unit/util/all.ts
- tests/unit/util/createDomWrapper.ts
First step towards custom elements. This PR contains two things,
* General purpose DOM element wrapping widget (`src/util/createDomWrapper`). Effectively this widget will just append a DOM element to itself..
* Methods to decorate a custom HTMLElement and tie it to a widget. The initializer will turn the HTML element into a projector with the widget as a child (see README for details).
What this PR does *not* contain is anything to perform the actual custom element registration. That will be somewhere....else.
Resolves: https://github.com/dojo/meta/issues/120
> Adding web components utilities, meta-120

- src/createWidgetBase.ts
- src/interfaces.d.ts
- tests/unit/createWidgetBase.ts
Resolves https://github.com/dojo/widget-core/issues/308
> Implement bind for widget properties

- src/interfaces.d.ts
**Type:** bug
Classes are not dealt with in widget base anymore, therefore shouldn't be on the base widget properties.
> Remove classes from base widget properties

- src/mixins/themeable.ts
- tests/unit/mixins/themeable.ts
**Type:** bug
BaseClasses is now a flat object again such that we can use the `typed-css-modules` cli and don't have to use `baseTheme.classes.className` and instead can use `baseTheme.className`.
> Changed BaseClassses shape and key to _key

- src/customElements.ts
**Type:** bug
Moving properties into widget construction of custom element, instead of afterwards.
> Moving properties into initialization

- src/mixins/createFormLabelMixin.ts
- tests/unit/mixins/createFormLabelMixin.ts
> FormLabelMixin: pass classes and label-specific attributes to the <label> node

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
**Type:** bug
Warn for an unknown registry item over throwing an error.
Resolves #332
> Warn for unknown widget registry item

- src/interfaces.d.ts
Adding types so you don't have to re-type event handler signatures all the time.
Old,
```ts
interface MyWidget {
onClick(event?: MouseEvent): void;
}
```
New,
```ts
interface MyWidget {
onClick: ClickEventHandler;
}
```
Resolves #240
> Adding helpful types for event handlers, issue #240

- src/mixins/Themeable.ts
- tests/unit/mixins/Themeable.ts
`classes` and chained `fixed` functions can now accept `null` as a class.
Resolves #336
> Added filter for null classes

- src/FactoryRegistry.ts
- src/WidgetBase.ts
- src/customElements.ts
- src/d.ts
- src/interfaces.d.ts
- src/mixins/FormLabel.ts
- src/mixins/I18n.ts
- src/mixins/Projector.ts
- src/mixins/Registry.ts
- src/mixins/Stateful.ts
- src/mixins/Themeable.ts
- src/registerCustomElement.ts
- src/util/DomWrapper.ts
- tests/functional/support/registerCustomElement.ts
- tests/unit/WidgetBase.ts
- tests/unit/d.ts
- tests/unit/util/DomWrapper.ts
Change the check for a Widget class type in order to avoid the cyclical dependency between `FactoryRegistry` and `WidgetBase` - will also require extracting interfaces out into the common interfaces.d.ts file.
Resolves #344
> Update check for Widget class type

- src/mixins/Projector.ts
- tests/unit/mixins/Projector.ts
**Type:** bug
This will allow you to override `afterCreate` on the projector and have both your method, and the projector's method, called.  This is sort of brute-forced in there, as I couldn't think of a clever way to use aspects for something like this, since the method itself is dynamic.
Resolves #323
> Allowing afterCreate to be called on the projector, issue #323

- src/mixins/FormLabel.ts
- tests/unit/mixins/FormLabel.ts
**Type:** bug
With the use of `render()` it no longer makes sense to have `type` on the instance, so I removed type entirely from FormLabel. The only widget that would use `properties.type` is `TextInput`, so it makes more sense to handle on a widget-by-widget basis.
> Remove type from FormLabel

- src/mixins/I18n.ts
- src/mixins/Projector.ts
- src/mixins/Stateful.ts
- src/mixins/Themeable.ts
**Type:** bug
Interfaces can be the same name as the function for mixins provided they are both exported from the same module. Also the Base class needs to be specified first for the return intersection type.
> Fix up mixin interfaces

- src/mixins/I18n.ts
- tests/unit/mixins/I18n.ts
Update the `I18n` mixin to add locales to an HTML element's `lang` attribute instead of to the custom `data-locale` attribute.
**Type:** bug
Resolves #353
> Set locales on `lang` attribute.

- src/WidgetBase.ts
- src/interfaces.d.ts
- tests/unit/WidgetBase.ts
Removes `id` from widget base
Resolves #337
> remove 'id' from widget base

- src/WidgetBase.ts
- src/customElements.ts
- src/mixins/Themeable.ts
- tests/unit/WidgetBase.ts
- tests/unit/d.ts
- tests/unit/mixins/FormLabel.ts
- tests/unit/mixins/I18n.ts
- tests/unit/mixins/Projector.ts
- tests/unit/mixins/Registry.ts
- tests/unit/mixins/Stateful.ts
- tests/unit/mixins/Themeable.ts
- tests/unit/util/DomWrapper.ts
As described by the issue, with the initial setProperties occurring in WidgetBase constructor it means that the first event is missed by sub classes and inadvertently promotes a pattern of putting logic in the constructor. This can be a problem for non decorator alternatives to decorators provided functionality, such as `@theme` as there is no reasonable way to ensure that `this.baseClasses` is available in in the mixins constructor.
This will become a core principle of Dojo 2 widgets, that only variable initialisation and listening to events (`.on`) should happen in the constructor.
Resolves #356
> Decouple initial set properties from the widget base constructor

- src/mixins/Themeable.ts
- tests/support/styles/overrideClasses1.css.ts
- tests/support/styles/overrideClasses2.css.ts
- tests/support/styles/testWidget.css.ts
- tests/support/styles/testWidgetTheme1.css.ts
- tests/support/styles/testWidgetTheme2.css.ts
- tests/support/styles/testWidgetTheme3.css.ts
- tests/support/styles/theme1.css.ts
- tests/support/styles/theme2.css.ts
- tests/support/styles/theme3.css.ts
- tests/unit/mixins/Themeable.ts
Convert themeable to lazily register classes as they are used instead of registering all the possible classes upfront and every time theme/overrideClasses changes.
Resolves #360
> Lazily register widget classes

- package.json
- src/mixins/Projector.ts
- tests/support/loadJsdom.ts
- tests/unit/mixins/Projector.ts
This removes our reliance on the Maquette projector, so we can now have more control over things such as event handling.
* Events now are listeners rather than handlers, this should mean no longer needing an `afterCreate` in widgets for things such as `transitionend`. As well as working with polyfills such as PEPjs.
* At the moment, maquette gives me no way to actually tear down event listeners on removal of a domnode - these should be garbage collected but we will have to see. 
* Event listeners are added on a per node basis, nothing clever. This may be problematic with a large number of listeners. I have code here: https://github.com/matt-gadd/widget-core/blob/projector-replace/src/mixins/Projector.ts#L150-L17 …
> Remove dependency on Maquette's Projector.

- README.md
- src/WidgetBase.ts
- src/mixins/FormLabel.ts
- src/mixins/I18n.ts
- src/mixins/Themeable.ts
- tests/unit/WidgetBase.ts
Add built in widget base support for decorators and support base functionality in non decorator environments. Add `@afterRender` and `@diffProperty` core decorator used like 
```ts
class MyWidget extends WidgetBase{
@diffProperty('foo')
diffFoo(previousProperty: any, newProperty: any) {
// do diff here
return {
changed: true,
value: 'myFoo'
}
}
@afterRender
addThingsToRenderResult(result: DNode) {
// do things here
return result;
}
}
```
With the equivalent functionality in a non decorator environment using `addDecorator` in the constructor.
```ts
class MyWidget extends WidgetBase{
constructor() {
super();
this.addDecorator('diffProperty', { propertyName: 'foo', diffFunction: this.diffFoo }); …
```
> Widget Base decorator support including `diffProperty` and `afterRender`

- README.md
- src/WidgetBase.ts
- src/mixins/Registry.ts
- src/mixins/Themeable.ts
- tests/unit/WidgetBase.ts
Adds support for a decorator to mark functions as listeners of the `properties:changed` event. Functions with `@onPropertiesChanged` the decorator will be called when the widgets `properties:changed` event is fired.
**Note:** In future we may expose a more generic decorator that could be used for all events, something like `@on('properties:changed')` from the core `Evented` class.
```ts
class MyWidget extends WidgetBase{
@onPropertiesChanged
myPropertiesChangedListener(evt: PropertiesChangeEvent<this, MyWidgetProperties>) {
// do things here on property change
}
}
```
Resolves #365
> Decorator that adds listeners for `properties:changed` event

- src/d.ts
- src/interfaces.d.ts
- src/mixins/Themeable.ts
- tests/unit/d.ts
- tests/unit/mixins/Themeable.ts
* Adds `VirtualDomProperties`, but doesn’t touch any of the existing `VNode` or `VNodeProperties` in `@dojo/interfaces`. We should raise an issue for removing these later.
* Switches the user facing properties for `v` to be `VirtualDomProperties`
As part of this I decided to implement #367 to prove that the forked interfaces work, which basically means:
* Changes the interface for `classes` in `VirtualDomProperties`
* Implements calling `classes` if its a function on the `VirtualDomProperties` object in `v`
* Make the result from the `this.classes` chain a function in themeable
Resolves #362 #367
> Move to VirtualDomProperties

- package.json
* Removes some dependencies which are peer deps but accidentally also committed as dependencies. 
* Removes `@dojo/stores` and `@dojo/compose` as no longer used in widget-core. 
* Removes `dts-generator` as not used and was throwing a warn of:
```
warning Incorrect peer dependency "typescript@^1.6.0".
```
> Remove some superfluous dependencies

- src/WidgetBase.ts
- src/mixins/Themeable.ts
Convert uses of array functions `forEach`, `reduce`, `map`, `filter` to simple `for` loops.
Whilst this may seem trivial the `render`, `this.classes` and `setProperties` pipeline can get executed thousands of times each lifecycle.
*Benchmark (20 Runs) - Adding 1000 Todos, Completing Todos (Individually) and Removing Todos (Individually)*
Chrome 56
Safari 10.0.3
Firefox 51
> `WidgetBase` and `Themeable` Array Optimisations

- README.md
Update the README to drop the requirement of using `.get()` when using `this.classes()` (which was added in https://github.com/dojo/widget-core/issues/367).
Also tidies up the whitespace.
> Update README to drop .get() from this.classes usage

- src/mixins/Registry.ts
- tests/unit/mixins/Registry.ts
**Type:** bug
The excluding from the main diff functionality was lost when we moved over to decorators. I've added the appropriate decorator and a unit test to prove the fix.
> Re-add registry mixin diff function lost with move to decorators

- src/WidgetBase.ts
- src/mixins/Themeable.ts
This reverts commit 661088e5313d4e596c4babefe6565103962e774a.
**Type:** bug
This change reverts the updates through `WidgetBase` and `Themeable` to use `for` loops. The changes were bugged, as `break;` was used where it should have been `continue;` (all unit tests passed 😞). Once these errors had been corrected the benchmark difference was negligible and therefore it is preferable to keep the newer array constructs.
> Revert "`WidgetBase` and `Themeable` Array Optimisations (#372)"

- src/mixins/Projector.ts
Switch to using event listeners over traditional handlers. The reasoning being so we can use polyfills such as the pointer events polyfill which don't support traditional handlers. Their is no tearing down of these listeners as maquette provides no mechanism, but they should be garbage collected on node removal anyway. No checking is done on whether the event is already added either, as the only time this would happen would be if the event handler function changed, in which maquette throws an error anyway (rule 1 of maquette http://maquettejs.org/docs/rules.html)
There are already unit tests which cover the event functionality, so none added in this PR
> Use addEventListener over traditional event handlers

- src/mixins/FormLabel.ts
**Type:** bug
Maquette's h() actually requires the `checked` property to be a boolean, not a string
> Maquette checked prop should be boolean

- package.json
- tsconfig.json
- typings.json
Remove dependency on symbol shim typings, requires https://github.com/dojo/core/pull/294 and https://github.com/dojo/i18n/pull/62 to be released.
Related to https://github.com/dojo/meta/issues/113
> Remove symbol-shim typings

- src/interfaces.d.ts
**Type:** Feature
Adds relevant interfaces for Pointer Events.
Refs https://github.com/dojo/meta/issues/141, https://github.com/dojo/meta/issues/59
> Add Pointer Event interfaces to VirtualDomProperties

- package.json
- src/mixins/Projector.ts
- tests/functional/support/registerCustomElement.html
- tests/intern.ts
- tests/support/loadJsdom.ts
This is to discuss, as its one of the few polyfills we actually have that are external and not from `dojo/shim`. I think we should include it by default in the projector, rather than it being opt-in. We've done similar with css-transitions and the projector, and pepjs is only 6kb min & gzipped.
> Include Pointer Event Polyfill with Projector

- src/mixins/Projector.ts
- tests/unit/mixins/Projector.ts
**Type:** bug
Resolves #397 
This adds back using event handlers for all known maquette events (defined in the interface), anything else will use `addEventListener`. This is really a temporary workaround until we get chance to work on a new way of attaching events without using the `eventHandlerIntercepter` (probably via `afterCreates` in `v`)
> Support both event handlers and event listeners

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
**Type:** bug
Fork behaviour for adding decorators functionality depending whether added programmatically or via typescript decorators.
Resolves #406
> Add attribute to sniff and fork addDecorator code depending caller

- src/d.ts
- src/interfaces.d.ts
- tests/unit/d.ts
We currently keep everything but the tag on the `HNode`. The tag may be useful in future for introspection of a `HNode` without having to call the `render` function on it.
> Add tag to HNode

- README.md
- src/WidgetBase.ts
- src/mixins/I18n.ts
- src/mixins/Registry.ts
- src/mixins/Themeable.ts
- tests/unit/WidgetBase.ts
- tests/unit/mixins/Themeable.ts
Enhancements to base decorators `theme`, `afterRender`, `onPropertiesChanged`, `diffProperty`.  This removes the usage of `this.addDecorator` and calls decorator methods directly:
```typescript
class MyWidget extends WidgetBase<any> {
constructor() {
super();
afterRender(this.afterFn)(this);
}
afterFn(node: any) {
return node;
}
}
```
As a side effect, we can also call `onPropertiesChanged` on a class level, rather than just a function level:
```typescript
function PropertyLogger() {
return onPropertiesChanged(function(event) {
console.log("Properties Changed", event);
});
}
@PropertyLogger()
class TestWidget extends WidgetBase<any> {
}
```
**Note that this is a breaking change as it requires all decorators …
> Decorator system enhancements

- src/d.ts
- tests/unit/d.ts
**Type:** bug
Moves the call to `properties.classes` when it's a function to outside the `render` on a `HNode`.
Resolves #433
> Call to create classes outside the render in 'v' when creating a 'HNode'

- src/mixins/Projector.ts
- tests/unit/lifecycle.ts
- tests/unit/mixins/Projector.ts
Making `attach` sync on the Projector.  Also removed the `projector:attached` event. As far as I can tell, the README is already treating the attach methods sync, so no changes there.
Resolves #427
> Making Projector.attach sync, issue #427

- README.md
- src/WidgetBase.ts
- src/interfaces.d.ts
- tests/unit/WidgetBase.ts
- tests/unit/mixins/Registry.ts
- Changed automatic property diffing to use `DiffType.AUTO`.
- Automatic diff logic is no longer overridable.
- Multiple `@diffProperty` decorators supported on a single property. Decorators run until a changed property is found.
Resolves #404
> Enhance property diffing system (refs #404)

- src/mixins/Projector.ts
- tests/unit/mixins/Projector.ts
Removing `render:scheduled` event from the projector. Since it was only used for testing, we can get away with reproducing the functionality with subclasses.
Resolves #430
> Removing render:scheduled event

- src/d.ts
- src/interfaces.d.ts
- tests/unit/d.ts
Extend `w` to make `properties` optional and allow `children` to be passed as the second parameter.
Resolves #439
> Align `w` API with `v` API

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
**Type:** bug
Do not bind widget constructors that are passed as parameters, doing so on iOS 9.3 and other older platform/browsers causes the static type used to sniff widget constructors to be erased.
A potentially more robust change would be to create an interface for the registry items, like:
```ts
export interface WidgetRegistryItemWrapper {
widgetConstructor?: WidgetConstructor | Promise<WidgetConstructor>;
lazyWidgetConstructor?: WidgetConstructorFunction;
}
```
Which means we can amend the `registry.define` API to accept the wrapper or similar.
```ts
define(widgetLabel: string, registryItem: WidgetRegistryItemWrapper): void;
```
I'm not sure how to test that a named function hasn't been bound to a scope (called …
> Do not bind widget constructors passed as parameters

- src/d.ts
**Type:** bug
Fix `w` overloads API.
Resolves #448
> Fix 'w' overload API

- src/WidgetBase.ts
- src/customElements.ts
- src/interfaces.d.ts
- src/mixins/Projector.ts
- tests/unit/WidgetBase.ts
- tests/unit/customElements.ts
- tests/unit/mixins/I18n.ts
- tests/unit/mixins/Projector.ts
- tests/unit/mixins/Registry.ts
- tests/unit/mixins/Themeable.ts
- tests/unit/util/DomWrapper.ts
Renames `setChildren` and `setProperties` to use the double underscore convention to indicate that even though they are public (through the need for widget-core to use them externally) they should not be called or overridden by consumers.
The projector is the only widget that requires direct use of either of these APIs and as such proxy methods `setProperties` and `setChildren` have been added to the API.
Resolves #447
> Update `setChildren` & `setProperties` to use the double underscore naming convention.

- src/RegistryHandler.ts
- src/WidgetBase.ts
- src/WidgetRegistry.ts
- src/mixins/Registry.ts
- tests/unit/RegistryHandler.ts
- tests/unit/WidgetBase.ts
- tests/unit/all.ts
- tests/unit/mixins/Registry.ts
This PR makes management and usage of Registries a little easier. The PR adds a few things:
* Support for arbitrary amount of registries, which are abstracted on usage (before we only supported a global and local registry, but then allowed overriding the local via a property using the `RegistryMixin`).
* `Registry.get()` no longer ever returns a promise, it either returns the widget or null.
* We no longer manage waiting on a registry item in `WidgetBase`, it's all dealt with by the `RegistryHandler`.
* You can now use before defining when using a widget from the `Registry` and the containing widget will re-render with it once it is loaded. This aligns more with Custom Elements.
With the above changes we now …
> RegistryHandler abstraction

- src/mixins/Themeable.ts
- tests/unit/mixins/Themeable.ts
The classes object will be calculated at the point that the `get` function is called not when `this.classes` is called.
```ts
render() {
const preCalculatedClasses = this.classes(css.classTwo);
return v('div', { classes: this.classes(css.classOne) }, [
v('span', { classes: preCalculatedClasses })
]);
}
```
Currently this would result in the `div` HNode including the negating class for the `preCalculatedClasses` like `{ classTwo: false, classOne: true }`. This is because `preCalculatedClasses` was created with `this.classes` first, which is confusing given the order of the classes in the render structure.
With this change the calculation is as lazy as possible and the classes will be memorised in an expected …
> Lazily calculate class object when `get` function is called.

- README.md
**Description:** Update README for use of `extraClasses`
Resolves #462
Note there are a few places in the text where we talk about overriding classes where changing the wording would not have made sense, so let me know if there's a suggestion on a different term to use in the places that still say override.
> refs #462, update overrideClasses to extraClasses

- src/WidgetBase.ts
**Type:** bug
Corrects the typings for `registries`
> Correct the typings for registries

- src/d.ts
- tests/unit/d.ts
**Type:** bug
The overloads on `w` actually remove the typing guards that are desired whilst using `w`. Additionally it seems to get for inference of the generic properties type from a widget class needed to add an intersection to the base `WidgetProperties` (props @matt-gadd)
Resolves #464
> Remove overloaded API and add intersection to WidgetProperties for `w`

- package.json
- src/Injector.ts
- src/RegistryHandler.ts
- src/WidgetBase.ts
- src/WidgetRegistry.ts
- src/d.ts
- src/interfaces.d.ts
- src/mixins/Container.ts
- src/mixins/I18n.ts
- src/mixins/Projector.ts
- src/mixins/Registry.ts
- src/mixins/Themeable.ts
- tests/unit/WidgetBase.ts
- tests/unit/d.ts
- tests/unit/mixins/Registry.ts
- tests/unit/mixins/Themeable.ts
- tsconfig.json
- tslint.json
Enhance the existing typings to enable the expected children of a widget to be typed; This includes the widget and the properties for the widget.
`WidgetBase` supports a second generic type for `children` and defaults to `DNode` but can be restricted to `WNode` (any widget or properties) or more specifically `WNode<MyChildWidget>`.
This change includes adding a default of `WidgetProperties` for the 1st generic argument, `P` in both `WidgetBase` and `WidgetBaseInterface`.
<p><details>
<summary><b>Examples</b></summary>
<div>
```ts
import { WidgetBase } from './WidgetBase';
import { WidgetProperties, WNode } from './interfaces';
import { w, v } from './d';
interface MyWidgetProperties extends WidgetProperties { …
```
> Support typing of widget children

- README.md
There is an extra space in one of the code examples in the README that at first glance, looks like a period should be a comma.  In fact, the space should not be there.
> Remove an extra space from the README.

- tests/unit/customElements.ts
**Type:** bug
An upstream change in maquette (raised by me) uses the `element.ownerDocument` instead of the global `document` when creating new elements.  This caused a regression in some tests where a mocked element was being used.  This adds the required property to fix those tests.
> Add ownerDocument to Element mock

- src/WidgetBase.ts
- src/mixins/Projector.ts
- tests/unit/WidgetBase.ts
- tests/unit/mixins/Projector.ts
**Type:** bug
Before, calling `invalidate` in either render or property phases (ie `diffProperty`), could cause undesirable behaviour (including infinite loops). We now guard against this by:
a) an `invalidate` during a render phase becomes a no-op.
b) an `invalidate` during the properties phase will mark the widget as dirty, but will not emit the invalidate the `invalidated` event up the tree.
> Adjust behaviour of invalidate during property and render phases

- src/RegistryHandler.ts
- src/WidgetBase.ts
- src/WidgetRegistry.ts
- src/d.ts
- src/interfaces.d.ts
- tests/unit/RegistryHandler.ts
- tests/unit/WidgetBase.ts
- tests/unit/WidgetRegistry.ts
- tests/unit/d.ts
Add support to use a `Symbol` as a key for defining an item in the registry and therefore when using `w`.
Requires https://github.com/dojo/core/pull/330
Resolves #478
> support symbol as a label for registries

- tests/functional/registerCustomElement.ts
- tests/intern.ts
**Type:** bug
MAC Safari 10 is failing for a driver issue, so bumping down to 9.1 and adding skips for the custom element functional tests (as not supported)
> Revert to use safari 9.1 and skip functional tests for safari

- src/WidgetBase.ts
- src/d.ts
- src/interfaces.d.ts
- tests/unit/WidgetBase.ts
- tests/unit/mixins/Projector.ts
- tests/unit/tsx.ts
Remove `bind` from both `WidgetProperties` and `VirtualDomProperties` interfaces and add capability in widget core to decorate all nodes for a widget with a `bind` value of the enclosing widget's scope.
Resolves #499
> Automatically add `bind` for all children nodes.

- package.json
- src/mixins/Projector.ts
- tests/functional/registerCustomElement.ts
- tests/unit/mixins/Projector.ts
This PR provides the ability to re-use the DOM when using `projector.merge()`.  This requires AFASSoftware/maquette#99.
When merging, it will automatically _hydrate_ the render with the DOM nodes.  It is obviously incumbent upon the developer to ensure that the DOM that is being merged follows the same structure of the virtual DOM.  If any of the DOM is missing, but described in the virtual DOM, maquette will create those DOM nodes.
An example.  It will initially render with the button disabled when it receives the HTML, but when the app loads and is merged, the button will become active.  In addition the text will change from `Hello!` to `Hello, Dojo World!`.  The DOM nodes will be reused:
**index.html** …
> Allow re-use of DOM when merging on Projector

- src/Injector.ts
- src/WidgetBase.ts
- src/mixins/Container.ts
- tests/unit/Injector.ts
Change `bind` to be a mandatory property for the `Injector` and add an `afterRender` to decorate all HNode/WNode with original `bind`.
Resolves #496
> Bind to the original widget instance for injectors.

- src/mixins/Projector.ts
- tests/unit/mixins/Projector.ts
**Type:** bug
Ensure properties and children are reset each render back to the last received set by either `setProperties` or `setChildren`
Resolves #498
> Ensure properties and children are 'reset' each render for a projector

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
**Type:** bug
Check that either previous children or current children exist before marking a widget as `dirty`.
Resolves #509
> Check children before setting widget as dirty

- README.md
- src/Injector.ts
- src/mixins/Container.ts
- src/mixins/Themeable.ts
- tests/unit/Injector.ts
- tests/unit/mixins/Themeable.ts
Adds support for globally defining the `theme` using a `Registry` and `ThemeInjector`. If the `theme` has been defined in the registry, it will inject the theme property into all themeable widgets that have not explicitly received a `theme` property.
When the `theme` is updated using the `.set` API of the theme context, all themeable widgets are invalidated.
Resolves #474
> Support for injecting a theme into Themeable widgets

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
- tsconfig.json
Adds the `constructor.name` of the widget that has been used multiple times without a unique key warning.
Resolves #505
> Include widget name in multiple widget warn message.

- src/Injector.ts
- tests/unit/Injector.ts
**Type:** bug
Use custom diff for render to always consider the property as changed. This is to ensure the when a widget that an Injector proxies invalidates that it will be re-rendered and not stop at the injector because it has not been considered "dirty"
Resolves #514
> Always re-render an Injector

- src/customElements.ts
- src/registerCustomElement.ts
- tests/functional/registerCustomElement.ts
- tests/functional/support/registerCustomElement.html
- tests/unit/customElements.ts
**Type:** bug
Creating a custom element manually (`document.createElement`) causes an error because elements are not supposed to be created with children (the projector). We're now deferring the appending of the projector until after the element is attached to the dom.
Resolves #517
> Deffering custom element children until after the node is created

- src/Container.ts
**Type:** bug
The mapper typings were causing a failure when built via cli-build (uses webpack and ts-loader).
```
ERROR in /Users/Anthony/routing-component/node_modules/@dojo/widget-core/Container.d.ts
(4,131): error TS2459: Type 'Partial<Mappers> | undefined' has no property 'getProperties' and no string index signature.
ERROR in /Users/Anthony/routing-component/node_modules/@dojo/widget-core/Container.d.ts
(4,146): error TS2459: Type 'Partial<Mappers> | undefined' has no property 'getChildren' and no string index signature.
```
Refactor the typings to play nicely.
> Refector typings round to play nicely with ts-loader

- src/registerCustomElement.ts
- tests/functional/registerCustomElement.ts
- tests/functional/support/registerCustomElement.html
Ensures that the correct instance is used when there is multiple custom elements of the same type.
Resolves #529
> Ensure that custom elements get the correct instance

- src/Injector.ts
- src/mixins/Themeable.ts
- tests/unit/Injector.ts
- tests/unit/mixins/Themeable.ts
Adds invalidation for injectors when the context is set using the `.set()` API.
Resolves #527
> Add invalidation when context is set

- README.md
- src/mixins/Projector.ts
- tests/unit/mixins/Projector.ts
This PR provides two additional APIs to the Projector to make it easy to perform server side rendering.
- `.sandbox()` - This will create a `DocumentFragment` that is used as the root for the projection.  This ensures any virtual DOM rendering does not impact the rendering of the global `document`.  It can take a single argument of type `Document` which can be used with something like `jsdom` where there is not a global `document` exposed.  It also switches the `Projector` into synchronous render mode, making it easier to ensure that when the projector is introspected, it is always in a fully rendered state.
- `.toHtml()` - Returns a `string` that provides the full HTML of the projection.  This method will …
> Add .sandbox() and .toHtml() to Projector

- src/Container.ts
- tests/unit/Container.ts
Change the `Container` to assume a `Partial` of the widget's properties that it is containing
Resolves #539
> Container should assume the widgets Properties as a Partial

- src/util/DomWrapper.ts
- tests/unit/util/DomWrapper.ts
**Type:** bug
Because `bind` is automagically passed via props (see: https://github.com/dojo/widget-core/issues/544), and i'm returning an empty object on the first render, this can cause maquette to not track the children correctly. To be safe always delete `bind` if it exists when passing to `v`.
> Remove bind when spreading properties in DomWrapper

- src/mixins/I18n.ts
- src/mixins/Projector.ts
- src/mixins/Registry.ts
- src/mixins/Stateful.ts
- src/mixins/Themeable.ts
- tests/unit/mixins/Themeable.ts
Currently it isn't possible add mixin capabilities unless an author has explicitly extended the relevant property interfaces at design time.
```ts
interface MyWidgetProperties extends WidgetProperties { }
class MyWidget extends WidgetBase<MyWidgetProperties> { }
```
As the widget's `MyWidgetProperties` doesn't extend the properties required for any mixin capabilities it means that the mixins cannot be used.
```ts
// errors as `MyWidgetProperties` does not extend `ThemeableProperties`
const MyThemeableWidget = ThemeableMixin(MyWidget); 
```
This change loosens the typings for mixins to accept `any` properties and adds an intersection to the return type to ensure that the extended widget has the correct property …
> Switch mixins to not require widgets to extend their properties interface

- src/util/DomWrapper.ts
- tests/unit/util/DomWrapper.ts
Resolves: https://github.com/dojo/widget-core/issues/547
https://github.com/dojo/widget-core/issues/549
> Add onAttached hook to DomWrapper

- src/mixins/Projector.ts
- tests/unit/mixins/Projector.ts
Adds support for all attach types to return either `null` or `string` from a top level projector. Maquette doesn't support changing the `vnodeSelector` of the root `VNode`, so need to ensure that they remain consistent when the top level node switches between a `VNode` and `null` or `string`.
For `merge`, if `null` or `string` is returned from `__render__` then a `VNode` is created using the `tagName` from the `root` node, with the `vnode.text` set for `string`s. When a `VNode`s is returned as the top level node, the `vnodeSelector` is set to the `root`s `tagName`.
Assuming a `root` node of `my-app`:
* Returning `null` will render `<my-app></my-app>`
* Returning `string` will render `<my-app>string</my-app>`
* …
> Support null and string render result from a projector

- package.json
- src/util/DomWrapper.ts
- tests/unit/util/DomWrapper.ts
Thanks to maquette (https://github.com/AFASSoftware/maquette/pull/103), we no longer need to do any dom replacement hacks in `DomWrapper`, this also has the nice side effect of resolving https://github.com/dojo/widget-core/issues/553. I have also added some supporting test cases. 
Resolves #553
> Simplify DomWrapper  

- src/WidgetBase.ts
- src/d.ts
- src/interfaces.d.ts
- src/mixins/Projector.ts
- tests/unit/WidgetBase.ts
- tests/unit/mixins/Projector.ts
Adds support to return an array of `DNode`s from a widget `render`, widgets used as a projector that return an array of nodes from the render will be automatically wrapped in a `span` (append and replace) or the tag name of the root DOM Element (merge).
Example Usage:
```ts
class MyListWidget extends WidgetBase {
protected render(): DNode[] {
return [
v('li', { key: '1' }, [ 'Item One' ]),
v('li', { key: '2' }, [ 'Item Two' ]),
v('li', { key: '3' }, [ 'Item Three' ]),
v('li', { key: '4' }, [ 'Item Four' ]),
v('li', { key: '5' }, [ 'Item Five' ]),
v('li', { key: '6' }, [ 'Item Six' ]),
v('li', { key: '7' }, [ 'Item Seven' ])
];
}
}
```
Resolves #533
> Support an array of `DNode`s from `render`

- src/Container.ts
- src/Injector.ts
- src/WidgetBase.ts
- src/mixins/Themeable.ts
- src/util/DomWrapper.ts
- tests/unit/Injector.ts
**Type:** bug
`bind` is a special internal property that gets decorated onto nodes return from `render`, this should not be available for consumers from `this.properties` - `bind` is not on the API but if the properties are spread then `bind` will get passed on without the consumer knowing.
`bind` is now removed from widget properties as part of the `__setProperties__` process and only used to bind functions that are passed in the `properties` object.
Renamed the `Injector` property `bind` to `scope` as this is public so we do want all the standard `__setProperties__` processing.
Resolves #544
> remove 'bind' from public consumer properties

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
In preparation for removing DOM access for nodes created and managed through the Dojo 2 widget system have added deprecation warnings for `onElementUpdated` and `onElementCreated` usage.
Part of #559
Resolves #557
> Add deprecation warning for onElementCreated and onElementUpdated usage

- src/RegistryHandler.ts
- src/WidgetRegistry.ts
- tests/unit/RegistryHandler.ts
- tests/unit/WidgetRegistry.ts
Support generics for registry and registry handler `get`.
Resolves #565
> Support generics on the registry

- src/mixins/Projector.ts
- src/util/eventHandlerInterceptor.ts
- tests/unit/util/all.ts
- tests/unit/util/eventHandlerInterceptor.ts
This PR breaks out `eventHandlerInterceptor` (see #445) and removes the touch events from the list of events that are passed through to maquette, and instead installs the listeners/handlers via the `.addEventListener` on the target DOM element directly.
Resolves #445
Resolves #563
> Breakout eventHandlerInterceptor and don't pass through touch events.

- README.md
- src/meta/Dimensions.ts
- tests/unit/meta/Dimensions.ts
- tests/unit/meta/all.ts
Adds dimensional meta using the new meta system. We can use this to get exciting things like node position and size!
```typescript
render() {
const dimensions = this.meta(Dimensions).get('someNode');
console.log('node width: ', dimensions.width);
// ...
}
```
> Meta dimensions

- src/mixins/Themeable.ts
**Type:** bug
Re-use the `ClassesFunction` from `src/interfaces`
Resolves #536
> Use ClassesFunction from interfaces

- src/WidgetBase.ts
- src/interfaces.d.ts
- tests/unit/WidgetBase.ts
Adds a guard for the `beforeRender` decorator if a function does not return a render method then the original render function is re-used.
Adds a guard for the `afterRender` decorator if a function does not return dNodes then the original dNodes function is re-used.
Resolves #522
> Add guards for beforeRender and afterRender for undefined return values

- src/WidgetBase.ts
- src/interfaces.d.ts
- src/mixins/Projector.ts
- tests/unit/WidgetBase.ts
- tests/unit/mixins/Projector.ts
Add support for `undefined` as a return type for `render` and `child`
Resolves #568
> Support undefined as type for DNode

- README.md
- src/Injector.ts
- src/WidgetBase.ts
- src/diff.ts
- src/interfaces.d.ts
- src/mixins/Registry.ts
- src/mixins/Themeable.ts
- tests/unit/WidgetBase.ts
- tests/unit/diff.ts
- tests/unit/mixins/Registry.ts
This PR changes the `diffProperty` decorator to add the concept of a reaction callback that is registered by using the decorator at a class method level. 
Diff functions are now passed via the second argument of the decorator and are required to **pure functions** with no side affects.
```ts
@diffProperty('foo', diffFunction)
class MyWidget extends WidgetBase {}
```
When the decorator is used at a method level it will register the function as the reaction callback that is called when one or more of the defined properties are considered changed. The function receives the previous and new properties for the registered keys.
```ts
class MyWidget extends WidgetBase {
@diffProperty('foo', diffFunction)
protected …
```
> Add reaction callback to custom `diffProperty`

- src/WidgetBase.ts
- src/interfaces.d.ts
- src/mixins/Projector.ts
- tests/unit/WidgetBase.ts
- tests/unit/mixins/Projector.ts
- tests/unit/mixins/Themeable.ts
Eventing for properties and children changes are not required. Replacing the listeners on these events by calling `scheduleRender` on invalidate and calling invalidate within the `__setProperties__` and `__setChlildren__` calls.
Resolves #589
> Remove events for properties and children changes

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
It was fine to warn when `undefined` was not a supported `DNode` value but now that `undefined` is a supported type, we cannot warn or automatically replace with the previous value.
Resolves #585
> Cannot warn or use the previous DNodes when a supported DNode type of `undefined` is returned.

- src/Injector.ts
- src/WidgetBase.ts
- tests/unit/Injector.ts
- tests/unit/WidgetBase.ts
- tests/unit/meta/Dimensions.ts
- tests/unit/meta/meta.ts
- tests/unit/mixins/Registry.ts
**Type:** bug
Attempt to enable use of Injectors to be used in a `@beforeRender()` with `meta` and local registries.
Resolves #595
> Enable Injector to work with Widgets the use local registries and meta

- src/Injector.ts
- src/WidgetBase.ts
- src/mixins/Registry.ts
- src/mixins/Themeable.ts
- tests/unit/WidgetBase.ts
- tests/unit/mixins/I18n.ts
- tests/unit/mixins/Registry.ts
**Type:** bug
Further support in `WidgetBase` and `Injector` to enable correct `afterRenders` to be executed when the original `DNode`s are returned from the `render` function passed to the `Injector`.
Breaking change as updated `this.registries` to `this.getRegistries()` so that `Injector` can override and call the `super.getRegistries()` with the original widgets scope passed as the properties.
Resolves #600
> Support original `afterRenders` when replacing render with an `Injector`

- src/mixins/Projector.ts
- tests/unit/mixins/Projector.ts
**Type:** bug
Adds support to type guarding of properties for the `ProjectorMixin` when using `setProperties`.
Resolves #613
> Support property type guards for 'setProperties' on the ProjectorMixin

- src/mixins/Themeable.ts
**Type:** bug
The `theme` property is typed as `any` when it could be typed as an index.  This would prevent people from accidentally assigning themes that are not valid.  I tried to type `injectedTheme` but there appears to be, likely, a code logic issue in that `Themeable._theme` is typed as `ClassNames` but there is also a comparison of `theme !== injectedTheme` in the code, which means that we are likely mis-handling something somewhere, but we should try to type `injectedTheme` and `extraClasses` with something that is more narrow than `any` as it is just too prone to downstream errors.
> Type theme property

- src/WidgetBase.ts
- src/mixins/Themeable.ts
- tsconfig.json
These changes are required to support improvements to `@dojo/shim`.  Outside of adding the `es6.promise` lib to the library, all the rest are forward compatible fixes dealing with potentially undefined values with the updated interfaces for the shim modules.
Refs: dojo/shim#101
> Updates for @dojo/shim

- src/WidgetBase.ts
- src/mixins/Themeable.ts
- tests/unit/mixins/Themeable.ts
Support typings for `extrasClasses` property on `ThemeableProperties`.
Resolves #603
> Support typings for ThemeableMixin extraClasses

- src/WidgetBase.ts
- src/d.ts
- tests/intern.ts
- tests/unit/WidgetBase.ts
Some performance tweaks based on the `js-framework-benchmark` results.
Before and after (tweak) results running on my mac with 20 iterations.
> Benchmark tweaks

- src/customElements.ts
- src/meta/Base.ts
- src/mixins/Projector.ts
- tests/support/loadJsdom.ts
- tests/unit/customElements.ts
- tests/unit/meta/Dimensions.ts
- tests/unit/meta/meta.ts
- tests/unit/mixins/Projector.ts
- tests/unit/util/DomWrapper.ts
`global` has been moved to shim.
> Use shim global

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
**Type:** bug
addDecorator called at the method level does not use decoratorMap to add class-level decorators to the cache.
Resolves #622
> Ensure _decoratorCache uses class-level decorators

- README.md
**Type:** bug
The anchor `dom-wrapper` did not match the `DOMWrapper` section with the `domwrapper` anchor.
> Anchor did not match

- src/Injector.ts
Creates a less restrictive base for Injectors, for use with libraries such as Redux.
Resolves #630
> loosen typings on context for a Injector

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
**Type:** bug
Ensure that `bind` and `afterCreate`/`afterUpdate` properties are decorated on the return from `render` rather than when they are processed to `VNode` in `WidgetCore`. This ensures that the scope and hook functions are from the widget that they are declared.
Resolves #633
> Bind functions passed to DNodes to the enclosing widget that they are declared

- src/mixins/Projector.ts
- tests/unit/mixins/Projector.ts
Allow the `async` mode to be set from outside the projector instance before it has been attached.
Resolves #645
> Support setting async mode

- README.md
**Type:** bug
Just a simple fix to an incorrect link in the README.
Resolves #???
> fix incorrect link in README

- src/interfaces.d.ts
Provides `prototype` and `name` on the `Constructor` interface which makes it easier for downstream code to work with a widget class/constructor function.
Resolves #437
> Add prototype and name to Constructor

- src/WidgetBase.ts
- src/meta/Base.ts
meta/Base extends Destroyable. Meta instances are set to owned by the widget instance.
Resolves #635
> Clean up meta instances

- src/WidgetBase.ts
- src/interfaces.d.ts
- src/meta/Base.ts
- tests/unit/meta/meta.ts
Removes aggressive `.requireNode` calls where they aren't needed.
Adds callback support to `.requireNode` and adds tests to ensure it works with asynchronous invalidation.
Resolves #607 
Resolves #639
> Update requireNode to accept a callback

- src/interfaces.d.ts
**Type:** bug
Changing the `Constructor` type to an interface and including `prototype` and `name` causing errors in downstream projects. Error:
```
src/timepicker/TimePicker.ts(164,14): error TS4023: Exported variable 'TimePickerBase' has or is using name 'Constructor' from external module "./development/dojo2/widgets/node_modules/@dojo/widget-core/interfaces" but cannot be named.
```
> revert: Add prototype and name to Constructor #647

- .gitignore
Add `package-lock.json` to `.gitignore`
> gitignore for package-lock.json

- src/Injector.ts
- src/WidgetBase.ts
- src/d.ts
- src/interfaces.d.ts
- src/mixins/Projector.ts
- tests/support/createTestWidget.ts
- tests/unit/Container.ts
- tests/unit/WidgetBase.ts
- tests/unit/mixins/Themeable.ts
Adds support for `coreProperties` and processes them before the normally `__setProperties__` phase.
Resolves #658
> Add support for core properties

- src/WidgetBase.ts
- src/decorators/beforeProperties.ts
- src/interfaces.d.ts
- tests/unit/all.ts
- tests/unit/decorators/all.ts
- tests/unit/decorators/beforeProperties.ts
Adds `beforeProperties` lifecycle hook that enables a user to inject properties into that will get processed through the properties lifecycle.
Resolves #660
> add beforeProperties lifecycle hook

- README.md
- src/meta/Matches.ts
- tests/support/sendEvent.ts
- tests/unit/meta/Matches.ts
- tests/unit/meta/all.ts
This PR provides a meta provider that can determine if a particular event's target is the rendered version of a particular virtual DOM's `key` property.
This is indented to allow widgets to "filter" events that may have bubbled up or to allow a widget to do a level of event delegation with the DOM without having to know specifically about its rendered DOM.
> Add Matches meta provider

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
**Type:** bug
Ensure a user defined registry takes precedence when there is no explicit default registry
Resolves #673
> Fix registry promotion

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
- tests/unit/lifecycle.ts
- tests/unit/mixins/Projector.ts
**Type:** bug
Fixes edge failures. Makes certain tests sync
Resolves #679
> Fix Edge failures

- src/WidgetBase.ts
- src/interfaces.d.ts
- src/meta/Base.ts
This PR updates the `WidgetProperties` interface so that `key` can be a number or a string. A new `KeyedWidgetProperties` interface was also added that extends `WidgetProperties` and makes `key` required.
Resolves #672
> Interface updates

- src/Registry.ts
- src/RegistryHandler.ts
- src/WidgetBase.ts
- src/d.ts
- src/decorators/inject.ts
- src/interfaces.d.ts
- src/mixins/Projector.ts
- tests/support/createTestWidget.ts
- tests/unit/Container.ts
- tests/unit/RegistryHandler.ts
- tests/unit/WidgetBase.ts
- tests/unit/decorators/inject.ts
- tests/unit/mixins/Projector.ts
- tests/unit/mixins/Themeable.ts
- tests/unit/tsxIntegration.tsx
The more that registries have been explored, the more apparent it has become that the main use cases will be to support lazy loading widgets and for injecting values into the widget tree.
These changes remove `registry` as a supported property for all widgets, so that a `registry` is only supported for a `projector` (or app level). This `registry` will be passed as the `baseRegistry` for all widgets within the projector tree. 
As well as the `baseRegistry`, each widget will have access to define entries into a local registry created per instance. These locally defined entries will take precedence over entries with the same label defined in the `baseRegistry`.
The `registries` property (the `RegistryHandler`) on …
> Simplify Widget Registries

- src/RegistryHandler.ts
- src/WidgetBase.ts
- tests/unit/RegistryHandler.ts
**Type:** bug
Ensure that the `globalPrecedence` flag is used when checking if registered widgets need invalidation.
Also removes the `diffProperty` for `registry`, as no longer required.
> use the global precedence when checking to invalidate

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
Expose `changedPropertyKeys` from `WidgetBase`. Set with the keys identified as changed during the diff process.
Resolves #670
> Expose changed property keys from WidgetBase

- Gruntfile.js
**Type:** bug
Since including the `tsxIntegration` test the `dist/umd` output is not flat and includes both `src` and `test` directories. It should be just contents of the `src` directory.
Would be resolved by https://github.com/dojo/grunt-dojo2/issues/137
Is there any reason why all files in the `test` directory can't be excluded by default?
```ts
exclude: [ 'tests/**/*' ]
```
> Exclude tsx test files

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
Removing the warnings for using onElement* protected functions, this will be re-addressed when we can support removing the hooks.
> remove deprecated warnings

- src/customElements.ts
- src/mixins/Projector.ts
- src/registerCustomElement.ts
- tests/unit/mixins/Projector.ts
**Type:** bug
Calling `scheduleRender` every time  `invalidate` is called is problematic in certain scenarios when a widget is wrapped by the `ProjectorMixin`.  
1) When the `widget` has a property registered with a custom diff that always returns changed as true i.e. `diffProperty('my-prop', always)`
2) Uses the new `@alwaysRender` decorator (such as the `Container` HOC). 
Currently this causes `projector` instances to continuously schedule a render, as `this.invalidate()` will be called for all `__setProperties__` calls.
Overriding `invalidate` in this way should not be needed, as a listener that calls `scheduleRender` is attached to `projector` instances' `invalidated` event. 
Instead this `invalidated` event can be …
> Do not call schedule render every invalidate, only on setting properties and children

- src/WidgetBase.ts
- src/decorators/afterRender.ts
- src/decorators/beforeProperties.ts
- src/decorators/beforeRender.ts
- src/decorators/diffProperty.ts
- src/decorators/handleDecorator.ts
- src/decorators/inject.ts
- src/mixins/I18n.ts
- src/mixins/Themeable.ts
- tests/unit/Container.ts
- tests/unit/WidgetBase.ts
- tests/unit/decorators/afterRender.ts
- tests/unit/decorators/all.ts
- tests/unit/decorators/beforeRender.ts
- tests/unit/decorators/diffProperty.ts
- tests/unit/mixins/Projector.ts
Move all decorators into their own modules in the `decorators` directory.
Resolves #683
> Move decorators out of WidgetBase

- package.json
- src/meta/Intersection.ts
- tests/intern.ts
- tests/support/loadJsdom.ts
- tests/unit/meta/Intersection.ts
- tests/unit/meta/all.ts
Builds on #664, updating to use the latest changes in meta (added by by #666).
It is highly likely the functionality will need to be enhanced to cater for the more advanced use-cases in the future.
Includes the intersection observer polyfil
Resolves #644
> Intersection Observer Meta

- README.md
**Type:** bug
Add sections for 
Resolves #669 
Resolves #671
> Update README Content

- src/mixins/Themeable.ts
- tests/unit/mixins/Themeable.ts
> Remove the stacked theme order reversal to support widget extension with new theme

- src/WidgetBase.ts
- src/mixins/Projector.ts
- tests/unit/mixins/Projector.ts
**Type:** bug
Calling `setProperties` or `setChildren` cause a render to occur on every RAF, this change adds flags to skip resetting the projector properties/children on the render after they have been set explicitly using the projector API `setProperties` and `setChildren`
Resolves #704
> Only schedule a Projector render when properties or children are set explicitly

- src/customElements.ts
**Type:** bug
Need to use the external projector API to set properties and children in custom elements.
Resolves #709
> Use external API for setting properties and children

- .gitignore
- package-lock.json
We shouldn't need to ignore the package-lock.json anymore, it causes a failure in the `grunt release` task as it is using `npm version` which implicitly tries to add the file to commit (and the release fails). As the peer dependencies are installed with a pre publish script we should always get the latest version according to the semver dependency version.
> Do not ignore package-lock.json

- src/meta/Drag.ts
- tests/unit/meta/Drag.ts
This PR enhances the Drag meta provider by providing a `start` property on drag results.  This start property is a matrix of positional information from the pointer event.  It therefore makes it possible to determine where the pointer location is by taking one of the properties of the `start` property and adding the `delta` property.
This is useful in cases where a render function needs to instantiate something at a particular location of where the pointer event is occurring.
Resolves #715
> Add start position information for a drag event

- package.json
- src/mixins/Themeable.ts
This PR uses the RC for TypeScript 2.5.  There are a couple minor changes where TypeScript has gotten a bit more strict on typing of some complex types.
References: dojo/meta#197
> Updates for TypeScript 2.5

- package-lock.json
- src/meta/Base.ts
- src/meta/Dimensions.ts
- src/meta/Drag.ts
- src/meta/Intersection.ts
- src/meta/Matches.ts
- tests/unit/meta/Dimensions.ts
- tests/unit/meta/Drag.ts
- tests/unit/meta/Intersection.ts
- tests/unit/meta/Matches.ts
**Type:** bug
This fixes all the meta providers so their `.get()` methods accepts `string | number` for keys.
Resolves #720
> Meta providers accept number or string keys

- src/meta/Drag.ts
- tests/functional/Drag.ts
- tests/functional/all.ts
- tests/functional/meta/Drag.html
- tests/functional/meta/Drag.ts
- tests/unit/meta/Drag.ts
**Type:** bug
This PR fixes issues with the Drag meta provider, where secondary button clicks (right clicks) would put the node into a drag state.  In addition it handles situations where a non primary pointer (e.g. two finger touch) occurs, which cancels the current drag state.
Resolves #717
> Fix Drag meta to properly model non-primary button or pointers

- README.md
README updates for the Themed changes
> Update README for Themed changes

- package-lock.json
- src/d.ts
- src/interfaces.d.ts
- src/vdom.ts
- tests/unit/d.ts
- tests/unit/vdom.ts
`v()` now supports a function as the second parameter (rather than just `VirtualDomProperties`). If a callback is passed, the callback will be called on render as per usual, and then again on the next `requestAnimationFrame`. This allows you to for example measure and apply changes to a property without having to trigger a full re-render, or change a style property to trigger a css transition. 
Example usage:
```typescript
v('div', (inserted /** the dom node has been inserted **/ ) => {
return {
opacity: inserted ? '1' : '0',
classes: [ 'fadeIn' ]
};
});
```
There are a few caveats which will likely be resolved in future:
* in lieu of a bonafide scheduler, there is nothing fancy here - it will simply queue a …
> Support deferred properties

- src/interfaces.d.ts
- src/mixins/Projector.ts
- src/vdom.ts
- tests/unit/mixins/Projector.ts
- tests/unit/vdom.ts
This PR addresses support to return a widget directly from a projector, an array of HNodes for `append` and `create` and the ability to swap the top level tag name of an Element.
The `domNode` that is returned by the projection is now not the node for the widget, it is the DOM element created or appended to. Except for merge which returns the DOM element that was the projection was merged on to.
An array is not supported by `merge` or `replace` and will throw an error.
Example renders that are now valid for use within a `Projector`:
```ts
// returning a widget at the top level
render() {
return w(MyWidget, {});
}
// returning an array of HNodes at the top level
render() {
return [
v('div', { key: '1' }), …
```
> Support returning top level widget, top level arrays and changing top level tag name

- src/interfaces.d.ts
- src/mixins/Themed.ts
- tests/unit/mixins/Themed.ts
**Type:** bug
The typings for a singular classname did not support `null`, while the multiple variance did in `Themed`. In `VirtualDomProperties` `classes` supported `null` across both, but the array version supported `undefined` also. The typings are now consistent across everything.
Functionally, passing `null` in an array to `this.theme` filtered it, while passing `null` singularly would log a warning. The functionality is now to not warn or filter consistently across both, as the filtering is done in `vdom` anyway.
> Tidy up consistency for singular and multiple classes

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
Only break early for matching `HNode`, not matching `WNode`s.
Resolves #742
> Only break early by node equality in `updateDom` for HNodes

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
Only merge onto an existing DOM structure for the initial render
Resolves #738
> Only merge on initial render

- src/interfaces.d.ts
- src/mixins/Projector.ts
- src/vdom.ts
- tests/unit/vdom.ts
Now we have these additional callback queues that run out of turn, we should make sure they run in sync when sync mode is enabled.
> Make sure vdom after callbacks run sync when in sync mode

- package-lock.json
- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
As per the investigation in #745, when a parent owns its widget children it creates a handle reference that is never severed and therefore the widgets are never available for garbage collection.
Removing the automatic `own` on child widgets enables children to be GC'd correctly once they are no longer in use.
Related to #745
> Do not own child widgets to ensure instances can be GC'd once they are no longer required

- src/customElements.ts
- tests/functional/registerCustomElement.ts
- tests/functional/support/registerCustomElement.html
- tests/functional/support/registerCustomElement.ts
- tests/unit/customElements.ts
If I'm understanding the code correctly, the widget won't render until it's attached to the projector. That happens [here](https://github.com/dojo/widget-core/blob/master/src/customElements.ts#L250), in the callback that gets called when the custom element is attached to the DOM. So until that point we don't need to worry about a `MutationObserver`, because we can just capture the state of the element when it's attached and set the appropriate children at that time. This has the added benefit of letting things like `replaceChild` and `insertBefore` work as expected, without a lot of additional logic.
If we want to be able to add children after the element is attached then we will probably need to track the …
> Move logic in custom element initialization

- src/customElements.ts
- src/registerCustomElement.ts
- tests/functional/registerCustomElement.ts
- tests/functional/support/registerCustomElement.html
Adds an event `connected` that is emitted once a custom element has connected.
```js
myCustomElement.addEventListener('connected', function() {
// do things once the element has connected
});
```
Resolves #754
> Add 'connected' event for custom elements

- src/meta/Intersection.ts
- tests/unit/meta/Intersection.ts
**Type:** bug
The intersection meta would not observe any nodes after the first called for a given `options` + `root` combination. This updates the logic so that `details` is only created once for each `options` + `root` combination but each new node requested is observed. A default value for details is provided for each node to avoid observing that node more than once.
Resolves #727
> Fix behavior for multiple nodes with the same root in intersection meta

- src/NodeHandler.ts
- src/WidgetBase.ts
- src/decorators/inject.ts
- src/interfaces.d.ts
- src/mixins/I18n.ts
- src/mixins/Projector.ts
- src/util/DomWrapper.ts
- src/vdom.ts
- tests/unit/NodeHandler.ts
- tests/unit/WidgetBase.ts
- tests/unit/decorators/inject.ts
- tests/unit/meta/Drag.ts
- tests/unit/meta/Matches.ts
- tests/unit/mixins/I18n.ts
- tests/unit/mixins/Projector.ts
- tests/unit/util/DomWrapper.ts
- tests/unit/vdom.ts
Removes `Evented` and `Destroyable` from `WidgetBase`, `WidgetBase` has been updated to accept an optional `invalidate` method in the `constructor` that will be called to propagate invalidation up the widget tree.
*Performance Comparison against master:*
*Memory Usage against master:*
Related to: #760
> Remove `Evented` and `Destroyable` from `WidgetBase`

- src/WidgetBase.ts
Simplify the set properties logic for the initial set properties 
Resolves #762
> Skip the main set properties logic for the initial properties set

- src/WidgetBase.ts
- src/mixins/Projector.ts
- src/vdom.ts
- tests/unit/WidgetBase.ts
- tests/unit/mixins/Projector.ts
- tests/unit/vdom.ts
**Type:** bug
Having an optional constructor argument for the parent invalidate function is unintuitive and horrible for end users needing to know that they have to pass the arguments on when anything is done in a widget constructor. Moves the injection of the parent invalidate function to a public setter that can only be set once.
The `WidgetBase` render state needs to be reset after running `__setProperties__()` and `__setChildren__()` in `Projector#scheduleRender()`
Related to #745
> Invalidator Fixes: Inject invalidator via setter and reset renderState in scheduleRender

- src/WidgetBase.ts
- src/mixins/Projector.ts
- src/util/DomWrapper.ts
- src/vdom.ts
- tests/unit/WidgetBase.ts
- tests/unit/vdom.ts
An instance `WeakMap` to vdom to share private/protected properties between widget instances and the vdom mechanism. Removes the need to publicly expose methods and properties from the instance just because they are required to process instances during the render process.
The next stage would be to remove all the existing double underscrore'd methods (for example `__setProperties__`) and reference them from the instance map. This will clean the WidgetBase API to simply `properties` and `children`
> Instance WeakMap for widgets in vdom

- src/customElements.ts
- src/util/DomWrapper.ts
- tests/unit/customElements.ts
For custom elements that are written to deal with Dojo 2 custom element children only, add support for widget-core to treat them as widgets meaning that they can be authored without needing to add specific code to deal with custom elements. 
**Enabling usage as follows:**
Using as a Dojo Widget:
```ts
class Example extends WidgetBase {
private _onSelected(data: any) {
console.log(data);
}
protected render() {
return w(Menu, { onSelected: this._onSelected }, [
w(MenuItem, { key: 'a', title: 'Menu Item A' }),
w(MenuItem, { key: 'b', title: 'Menu Item B', selected: true }),
w(MenuItem, { key: 'c', title: 'Menu Item C' })
]);
}
}
```
Using as a Custom Element:
```html
<demo-menu id="menu">
<demo-menu-item id="a" …
```
> Custom element wrapper

- README.md
- src/WidgetBase.ts
- src/vdom.ts
- tests/unit/vdom.ts
Adds two lifecycle methods `onAttach` and `onDetach` for when a widget has attached and when it is detached.
Resolves #766
> Add `onAttach` and `onDetach` lifecycle hooks

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
If `rendered` doesn't exist for the `WNode`, check the next old child if it exists otherwise break.
Resolves #775
> Bug: Ensure correct `insertBefore` is correctly calculated

- tests/run.html
Fixes the incorrect file path in `run.html`
> Correct run.html path

- src/vdom.ts
- tests/unit/vdom.ts
To enable enhancements to the render algorithm it is necessary to pass the parent DNode instead of the parent DOM Node.
As part of these changes `checkDistinguisable` no longer throws an error for non unique sibling nodes, a warning is logged to the console to mirror the behaviour if there are non unique widgets detected.
`checkDistinguisable` is also now runs on `requestIdleCallback`.
No functional changes delivered as part of these changes
> Pass parent DNode over domNode when processing the vdom tree

- src/WidgetBase.ts
- src/vdom.ts
- tests/unit/WidgetBase.ts
- tests/unit/decorators/diffProperty.ts
- tests/unit/mixins/Projector.ts
There is no need to even attempt to render in `vdom` if a widget is not dirty, we can now use the `dirty` flag from the widget `instanceData` contained in the `widgetInstanceMap`
Resolves #779
> Skip render call if widget is not dirty

- src/customElements.ts
- src/decorators/customElement.ts
- src/registerCustomElement.ts
- tests/functional/customElement.ts
- tests/functional/decorators/customElement.html
- tests/functional/decorators/customElement.ts
- tests/functional/decorators/noCustomElement.html
- tests/unit/customElements.ts
Updates the custom element decorator so that it only registers the element if `__dojoCustomElements__` is defined. Also fixes some issues with the simplified attribute configuration.
> Fix custom element decorator

- package-lock.json
- package.json
- tests/unit/WidgetBase.ts
- tests/unit/customElements.ts
- tests/unit/d.ts
- tests/unit/tsx.ts
- tests/unit/tsxIntegration.tsx
**Type:** bug
Intern now uses the new typings for chai which conflict with the pinned ones.
> Remove dependency on chai and use what comes with Intern

- src/mixins/I18n.ts
- src/mixins/Themed.ts
- tests/unit/mixins/I18n.ts
Updates the `I18n` mixin to use the injector pattern for passing locale data to children and removes the locale observer from the `I18n` constructor.
Resolves #781
> Update I18n mixin to use injector pattern.

- src/RegistryHandler.ts
- src/WidgetBase.ts
- tests/unit/RegistryHandler.ts
- tests/unit/WidgetBase.ts
**Type:** bug
Internal resources; registryHandler and associated meta instances for a WidgetBase instance need to be torn down when it is detached.
Resolves #799
> Ensure that meta and registry resources are torn down when a widget is detached

- src/WidgetBase.ts
- tests/unit/vdom.ts
Reset the render state to IDLE if there are no properties considered "changed" during diffing.
Resolves #796
> Reset Render state if widget is not considered dirty during setProperties

- README.md
- src/Registry.ts
- src/WidgetBase.ts
- src/decorators/handleDecorator.ts
- src/decorators/registry.ts
- tests/unit/Registry.ts
- tests/unit/decorators/all.ts
- tests/unit/decorators/registry.ts
Allows registry items to be defined via a decorator.
Also, `Registry` will automatically look for a widget constructor as the `default` import when an esModule is loaded.
Example:
```ts
@registry('reg-widget-1', Widget1) // single widget
class TestWidget1 extends WidgetBase {
render() {
return w('reg-widget-1', {}); // will render Widget1
}
}
@registry({
'reg-widget-1': Widget1,
'reg-widget-2': Widget2
}) // multiple widgets
class TestWidget2 extends WidgetBase {
render() {
return [ w('reg-widget-1', {}), w('reg-widget-2', {}) ];
} // will render Widget1, Widget2
}
```
Registry decorator can also accept promises the same way that the standard registry does ie.
```ts
@registry('reg-widget-1', () => …
```
> 652 - Registry decorator

- src/interfaces.d.ts
- src/meta/WebAnimation.ts
- tests/unit/meta/WebAnimation.ts
Moves the `AnimationProperties` used by the `WebAnimation` meta out of interfaces. Casts as the polyfilled type upon usage to avoid issues.
Breaking as it changes location of the interfaces.
Resolves #802
> 802 - Animation Timing Properties cast correctly

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
Check `rendered` children on `WNode` before calling `callOnDetach`.
Resolves #813
> Check for rendered children before calling onDetach

- src/vdom.ts
- tests/unit/vdom.ts
Moved `initPropertiesAndChildren` in `vdom`'s `createDom` before the node is inserted into the DOM to prevent triggering observers and custom elements on an incomplete DOM. More details in the ticket.
Resolves #816
> Moved initPropertiesAndChildren before inserting into the DOM

- README.md
- package-lock.json
- src/Container.ts
- src/WidgetBase.ts
- src/decorators/alwaysRender.ts
- tests/unit/Container.ts
- tests/unit/decorators/all.ts
- tests/unit/decorators/alwaysRender.ts
Add support `alwaysRender` decorator that will cause the widget to always re-render regardless of whether there are any property diffs.
Using the decorator for `Container` resolves the an issue that causes the the rendering to get caught in a loop instead of overriding the `__setProperties__` `WidgetBase` API.
Resolves #821
Resolves #676
> alwaysRender Decorator

- src/Registry.ts
- tests/unit/Registry.ts
Supports required typings to register an item of `() => import('./MyWidget')` that has a default export.
Resolves #828
> Fix registry typings

- src/interfaces.d.ts
Use `Partial<CSSStyleDeclaration>` type for `styles` on `VNodeProperties`
> Add typings for `styles` on `VNodeProperties`

- intern.json
- package-lock.json
- package.json
Moves the web animation types from a dev dependency to a dependency in package.json and removes the web animations config from intern.json as this will be provided by shim.
Relies on: https://github.com/dojo/shim/pull/128
> Move web-animations typings as dep and remove intern config for polyfill

- tests/support/util.ts
- tests/unit/NodeHandler.ts
- tests/unit/meta/Dimensions.ts
- tests/unit/meta/Intersection.ts
- tests/unit/meta/WebAnimation.ts
- tests/unit/meta/meta.ts
- tests/unit/vdom.ts
Sinon v4 warns that `.reset()` is deprecated
> Update deprecated sinon.reset()

- package-lock.json
- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
**Type:** bug
Ensures that properties are only diffed once during `__setProperties__`.
Resolves #835
> Ensure that properties are only diff'd once when setting properties.

- src/WidgetBase.ts
- src/util/DomWrapper.ts
- src/vdom.ts
- tests/unit/vdom.ts
Removes the `onElementCreated` and `onElementUpdated` escape hatch that provides consumers with DOM nodes for nodes created with a `key`.
Related to #557
> Remove onElementCreated and onElementUpdated hooks

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
Moves the initial deferred properties call to before nodes are compared for equality.
Resolves #842
> Run deferred properties before checking nodes for equality

- src/customElements.ts
- tests/unit/customElements.ts
**Type:** bug
Check for child node instance immediately and only listen to child connected event if it hasn't been initialised.
Resolves #850
> Render immediately if the child widget instance of custom element is available

- src/interfaces.d.ts
- src/vdom.ts
- tests/unit/vdom.ts
Adds support in `vdom` for a focus property that calls focus on the next rAF if the property is `true` and was `false` in the previous render or the function returns `true`
Resolves #847
> Support `focus` on `VNodeProperties`

- src/customElements.ts
- src/util/DomWrapper.ts
- src/vdom.ts
- tests/unit/customElements.ts
- tests/unit/util/DomWrapper.ts
- tests/unit/vdom.ts
**Type:** bug(s)
* Support `TextNodes` as children to custom elements
* Initialise properties when custom element is hydrated
Resolves #849 
Resolves #805
> Support text nodes and initialise widget properties from the custom element node

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
Guard against a `VNode` that has no tag or or `text`.
> Ensure that vnodes with no tag or text are ignored by the vdom system

- src/decorators/customElement.ts
- tests/functional/decorators/customElement.ts
- tests/unit/decorators/customElement.ts
- tests/unit/vdom.ts
**Type:** bug
Update the types so that `WidgetProperties` is implicitly added to the allowed keys when using the custom element decorator.
Resolves #855
> Allow generic for properties on custom element to not extend WidgetProperties

- src/meta/Focus.ts
- tests/unit/meta/Focus.ts
**Type:** bug
Realized invalidating only on `focusin` events misses certain types of blur (e.g. tabbing out of the document into browser chrome, or when focus shifts to `body` in the time between mousedown and mouseup events)
> invalidate Focus meta on focusout events

- src/d.ts
- src/mixins/I18n.ts
- tests/unit/d.ts
- tests/unit/mixins/I18n.ts
* Support for a `breaker` function that can be called in a modifier to drain the queued nodes and exit decoration.
* Supports a `shallow` flag passed in the `DecorateOptions` (new API) to indicate that the `predicate` and `modifier` should only be run against the top level node or nodes.
* Backwards compatible with the existing API, however the existing API does not support the new `shallow` functionality.
Utilises the breaker for `i18n` to break after adding the `i18n` properties to the first `VNode` found.
Resolves #685 
Resolves #846
> Allow consumer to break from the decorate function and support shallow

- README.md
Updates `Themeable` references to `Themed` and adds section for `Intersection` and `Animation` metas
Resolves #860
> Add intersection meta to readme

- src/meta/WebAnimation.ts
**Type:** bug
- Changes AnimationProperties to allow array of functions or properties.
- Types the `effects` array (currently any)
Resolves #814
> Fix incorrect typings for WebAnimations

- src/meta/WebAnimation.ts
**Type:** bug
Adds missing brackets in WebAnimation Effect typings.
> Missing brackets in Effect typings

- src/vdom.ts
- tests/unit/vdom.ts
Ensure that properties are set even if the the domNode already has the same value (defaulted), move the domNode property value lookup to only happen for the two identified edge cases.
Also prevent `key` from being added to the domNode attributes.
> Ensure properties are set when they differ from the previous properties

- package-lock.json
- src/mixins/I18n.ts
- tests/unit/mixins/I18n.ts
- tests/unit/vdom.ts
**Type:** bug
Default `dir` to `''` over `null` as edge and IE11 throws an error when it is set to anything other than the allowed enums (`''`, `ltr`, `rtl` and `auto`)
Resolves #879
> Default `dir` property to zero length string

- src/registerCustomElement.ts
- tests/unit/registerCustomElement.ts
**Type:** bug
To ensure that custom elements needless re-render, use the `dom` diffType to check against the existing DOM property values
> Use diffType `dom` for custom elements

- src/Registry.ts
**Type:** bug
`import()` returns a promise of an object with `default`, but currently the typings are expecting `__esModule` as well which means the following fails for typings.:
```ts
registry.define('widget', () => import('./Widget'));
```
> fix typings for registry.define using imports

- src/d.ts
**Type:** bug
The common usage for `v()` is to use `VNodeProperties` over deferred properties, this re-orders the overloads so that it gives error information against `VNodeProperties`.
Resolves #843
> Reorder the overloads for v() so that it gives error information against VNodeProperties

- package-lock.json
- src/interfaces.d.ts
- src/vdom.ts
**Type:** bug
Projector state should not be able to get into an inconsistent state across the widget tree. This change extracts all top level projector state to a separate map to ensure that cannot occur.
Resolves #882
> Extract projector state from projection options

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
Fixes an issue with placing registry items on a subsequent render in which they have been loaded in the registry since the previous render. It does this by never considering WNodes as the the same in the comparison if they previous has not got an instance and the current has a string `widgetConstructor`.
Resolves #887
> Ensure registry items are placed in the correct order once they are loaded

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
Sets the `merge` flag to `false` after the initial render to ensure subsequent nodes are rendered correctly.
Resolves #889
> Only perform merge for initial render

- src/WidgetBase.ts
- src/decorators/inject.ts
- src/mixins/Projector.ts
- tests/unit/decorators/inject.ts
**Type:** bug
Moves `own` and `destroy` from `Projector` to `WidgetBase` (is then inherited from `WidgetBase` for the `Projector`) and the inject listeners are `own`ed so that they are removed when the widget is destroyed.
Resolves #891
> Remove inject listener when widget is destroyed

- src/vdom.ts
- tests/unit/vdom.ts
Updates the algorithm used to update, insert, remove and move nodes during `updateChildren` so that only affected nodes are actually removed.
Currently when a node is moved, the algorithm will remove all child nodes up to the index of the moved node in the old children list.
Consider 6 child nodes rendered: `[1, 2, 3, 4, 5, 6]`
If node `5` is moved to between after node `2` the current algorithm will remove nodes `3` and `4` even though they still exist in the new children list.
This change ensures that the system does not remove nodes that still exist in the new children.
**Swapping row 2 and row 7**
Existing behaviour:
Updated behaviour:
Moving row from end of list to beginning and inserting 4 rows:
Existing …
> Optimize algorithm using for updating children

- README.md
Fix example to use the correct [property name](https://github.com/dojo/widget-core/blob/master/src/decorators/customElement.ts#L40).  I noticed the error in the same example in the recent [blog post](https://dojo.io/blog/2018/03/11/2018-03-11-Dojo-2-rc1/) and was confused why one name would be singular when the others (`events`, `properties`) were plural.
> Fix customElement property name in README.md

- intern.json
**Type:** bug
The drag functional tests are failing from FF version 59.0 - I suspect there is an incompatibility between drivers/versions etc somewhere as the test works locally on version 59.0.
Have pinned the browser version to 58.0.
> Pin version of FF for tests

- package-lock.json
- src/decorators/customElement.ts
- src/registerCustomElement.ts
- tests/unit/decorators/customElement.ts
- tests/unit/registerCustomElement.ts
Adds `registryFactory` to `@customElement` options so that a custom registry can be passed for custom elements. It is optional, if not passed then an internal registry is created as before.
> Support registry factory for custom elements

- src/WidgetBase.ts
- src/registerCustomElement.ts
- tests/unit/WidgetBase.ts
- tests/unit/registerCustomElement.ts
**Type:** bug
When writing widgets using widget-core, we try to automatically bind properties that are functions to the widget scope so users don't have to. This works well within the widget authoring system, but becomes problematic if the function is passed from outside the system, in this case Custom Elements where the function could've come from anywhere. 
To avoid binding external functions, we unfortunately need to tag it with a global symbol so we can differentiate them. If they are tagged with the no bind symbol then WidgetBase will not bind the function at all. I feel a bit uneasy about modifying external functions even if it's just adding a symbol, and in the long run we should perhaps invert the logic so WidgetBase …
> Allow properties that are functions to be not automagically bound

- src/registerCustomElement.ts
- tests/unit/registerCustomElement.ts
**Type:** bug
We did not correctly support function properties (not events) with a prefix of `on`.
> Handle properties prefixed with on for Custom Elements

- README.md
- src/Injector.ts
- src/Registry.ts
- src/RegistryHandler.ts
- src/decorators/inject.ts
- src/interfaces.d.ts
- src/mixins/I18n.ts
- src/mixins/Themed.ts
- tests/unit/Container.ts
- tests/unit/Injector.ts
- tests/unit/Registry.ts
- tests/unit/RegistryHandler.ts
- tests/unit/WidgetBase.ts
- tests/unit/decorators/all.ts
- tests/unit/decorators/inject.ts
- tests/unit/mixins/I18n.ts
- tests/unit/mixins/Themed.ts
- tests/unit/registerCustomElement.ts
It has been identified that the ergonomics around using an `Injector` class as the base type when defining an injector in a registry can be awkward. 
* It requires consumers to deal with `Evented.emit()`, unlike everywhere else in Dojo 2, where we tend to provide abstractions on top of listening and emitting events.
* Additionally it was awkward to just provide a static payload that never needed to be reset.
* It encouraged consumers to extend the `Injector` class and make it stateful which was never the intention.
This change moves to accepting a functional factory that gets provided an invalidator and returns a function that when called will return the intended payload to be injected into the registered …
> Functional Factory Injector

- package-lock.json
- src/d.ts
- src/vdom.ts
- tests/unit/vdom.ts
Use reference equality check against domNodes for vnodes created using the `dom()` pragma. 
Resolves #916
>  Reference check dom nodes for vnodes created using the dom() pragma

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
Ensure that animations are called for DOM nodes within a widget, when the widget is added or removed.
Resolves #919
> Execute animations for nodes when a widget is added or removed

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
`vdom.ts` was processing widgets that had been detached by a previous render but had been invalidated themselves and therefore were already on the queue. To resolve this the call to "detach" widgets has been moved from request idle callback to be sync when processing renders. When a node it removed, `onDetach` is called which removes all references such as an injector that would otherwise invalidate the detached widget and also removes the instance from the `instanceMap` so that it will not get rendered again.
Also when processing nodes from higher in the dnode tree, there was a possibility that an incorrect reference (to the old node) could be used as the render process was traversing down the tree of the parent …
> Fixes vdom issues with selecting insert before and rendering widgets after they have been destroyed

- README.md
- src/mixins/I18n.ts
- tests/unit/mixins/I18n.ts
Add an `overrideBundle` property to the `I18n` mixin properties allowing the base bundle to be overridden, or specific bundles to be overridden in the event that a widget derives its messages from multiple bundles. `overrideBundle` can a complete bundle, an object with a `locales` loader object that will be merged with the widget's default bundle, or a `Map` of default bundles to override values.
Resolves #901
> Allow widget i18n bundles to be overridden

- src/meta/Resize.ts
- tests/unit/meta/Resize.ts
Allows the ResizeObserver to not have to take a predicate, which means that you can do
```ts
this.meta(Resize).get('root');
```
and this will invalidate any time a resize occurs on the element. it would've been nice if this was the default scenario and we could actually return the `contentRect`, but that would be a breaking change to the return interface.
> Allow Resize meta to take no arguments which just invalidates on Resize

- README.md
The section "classes and theming" is now called "Styling and Theming" and also the anchor changed to `#styling--theming`
> corrected wrong anchor link

- src/vdom.ts
- tests/unit/vdom.ts
When iterating through the children of a node being removed, for `WNode`s currently the rendered nodes are taken from the node passed to the function - with subtree rendering this node could be different to the latest rendered node, so means not all the nodes are destroyed as expected.
To resolve this issue, ensure that the latest version of the node is used from the `instanceMap`
Resolves https://github.com/dojo/routing/issues/139
> Ensure that latest version of rendered node is used when destroying

- src/WidgetBase.ts
- tests/unit/WidgetBase.ts
**Type:** bug
Do not return when there are afterRender decorators on a widget.
Resolves #934
> Ensure meta after renders are called when a widget uses the afterRender decorator

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
For a widget that returns an array of nodes adding additional nodes in a subsequent render results in the nodes being added to the end of the parent DOM element. The cause of this is that when rendering the widget it has no knowledge of the DOM nodes that have been rendered by it's siblings and therefore doesn't find a candidate when calculating the DOM node to insert before.
This change makes sibling information available such that the insert before DOM node can be correctly calculated.
Resolves #930
> Inserting nodes when returning array from a widget

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
When calculating insert before, ensure that the correct WNode reference is used from the instanceMap. If a widget has had subtree rendered that removes the DOM node then the children reference of the parent will not be the latest version of the WNode and will possibly contain orphaned domNodes.
> Ensure the correct DNode it used when calculating insertBefore DOM Node

- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
Use `findIndexOfChild` to determine the index of a node amongst its siblings on a render.
Resolves #930
> Ensures that the dnodes index is found when selecting siblings

- intern.json
- src/vdom.ts
- tests/unit/vdom.ts
**Type:** bug
Optimistically store the array of "next" siblings for a widget instance to ensure that the correct node can be calculated to insert nodes before. The insert before logic iterates through these siblings and uses the first `domNode` located before hitting a `domNode`, if no candidate is found then the node will simply be appended to the parent.
Resolves #930
> Fix the algorithm for determining the position to insert new DOM nodes

- README.md
**Type:** bug
This is just a simple README fix.
> fix incorrect equality check in README

- src/meta/Drag.ts
- tests/support/sendEvent.ts
- tests/unit/meta/Drag.ts
Currently when you drag, the pointer events just pass right through. This can cause text on the page to become highlighted during a drag operation.
> Preventing default on drag events

- README.md
- src/mixins/Focus.ts
- tests/unit/mixins/Focus.ts
- tests/unit/mixins/all.ts
`FocusMixin` builds on the primitive `focus` functionality provided by `vdom` and enables management of focus across widget boundaries.
The `FocusMixin` provides a function called `shouldFocus` that manages when a widget or their child widgets can apply focus, `shouldFocus` will only return `true` the first time it is called until `focus` is called again on the widget.
> Feature: Focus Mixin

- src/mixins/I18n.ts
- tests/unit/mixins/I18n.ts
Fix for i18n adding `lang="null"` attributes, making a11y tests fail!
Resolves https://github.com/dojo/widget-core/issues/904
> I18n should not longer be creating null attributes

- README.md
Small typo which pointed you to the wrong animation section.
> Dropped 's' from Animations link to point to the right section

- src/interfaces.d.ts
- src/vdom.ts
- tests/unit/vdom.ts
Expands the existing vdom support for `focus` to support `blur`, `scrollIntoView` and `click`
> Extend the support for DOM Node operations in vdom

- src/meta/Intersection.ts
- tests/unit/meta/Intersection.ts
Resolves #953
**Type:** bug
Resolves #953
> Call observer.disconnect() in a closure to prevent invalid invocation

- src/decorators/diffProperty.ts
- tests/unit/decorators/diffProperty.ts
Default the diff on `diffProperty` to `auto`
> Default to auto diff for diffProperty

- README.md
Note this could be made clearer if @dojo/shim/browser had Resize Observer and Custom Elements shims, and if it was clear which polyfill we recommend for Resize Observer.
[ci skip]
**Type:** documentation
Resolves #913
> Fixes #913, add polyfill info to readme.
